
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AccountEntry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AccountEntry
 * 
 */
export type AccountEntryModel = runtime.Types.Result.DefaultSelection<Prisma.$AccountEntryPayload>

export type AggregateAccountEntry = {
  _count: AccountEntryCountAggregateOutputType | null
  _avg: AccountEntryAvgAggregateOutputType | null
  _sum: AccountEntrySumAggregateOutputType | null
  _min: AccountEntryMinAggregateOutputType | null
  _max: AccountEntryMaxAggregateOutputType | null
}

export type AccountEntryAvgAggregateOutputType = {
  id: number | null
  accountId: number | null
  paymentId: number | null
  movementId: number | null
  amount: runtime.Decimal | null
}

export type AccountEntrySumAggregateOutputType = {
  id: number | null
  accountId: number | null
  paymentId: number | null
  movementId: number | null
  amount: runtime.Decimal | null
}

export type AccountEntryMinAggregateOutputType = {
  id: number | null
  accountId: number | null
  paymentId: number | null
  movementId: number | null
  amount: runtime.Decimal | null
  entryType: $Enums.EntryType | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccountEntryMaxAggregateOutputType = {
  id: number | null
  accountId: number | null
  paymentId: number | null
  movementId: number | null
  amount: runtime.Decimal | null
  entryType: $Enums.EntryType | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccountEntryCountAggregateOutputType = {
  id: number
  accountId: number
  paymentId: number
  movementId: number
  amount: number
  entryType: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AccountEntryAvgAggregateInputType = {
  id?: true
  accountId?: true
  paymentId?: true
  movementId?: true
  amount?: true
}

export type AccountEntrySumAggregateInputType = {
  id?: true
  accountId?: true
  paymentId?: true
  movementId?: true
  amount?: true
}

export type AccountEntryMinAggregateInputType = {
  id?: true
  accountId?: true
  paymentId?: true
  movementId?: true
  amount?: true
  entryType?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type AccountEntryMaxAggregateInputType = {
  id?: true
  accountId?: true
  paymentId?: true
  movementId?: true
  amount?: true
  entryType?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type AccountEntryCountAggregateInputType = {
  id?: true
  accountId?: true
  paymentId?: true
  movementId?: true
  amount?: true
  entryType?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AccountEntryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccountEntry to aggregate.
   */
  where?: Prisma.AccountEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountEntries to fetch.
   */
  orderBy?: Prisma.AccountEntryOrderByWithRelationInput | Prisma.AccountEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccountEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AccountEntries
  **/
  _count?: true | AccountEntryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AccountEntryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AccountEntrySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccountEntryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccountEntryMaxAggregateInputType
}

export type GetAccountEntryAggregateType<T extends AccountEntryAggregateArgs> = {
      [P in keyof T & keyof AggregateAccountEntry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccountEntry[P]>
    : Prisma.GetScalarType<T[P], AggregateAccountEntry[P]>
}




export type AccountEntryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountEntryWhereInput
  orderBy?: Prisma.AccountEntryOrderByWithAggregationInput | Prisma.AccountEntryOrderByWithAggregationInput[]
  by: Prisma.AccountEntryScalarFieldEnum[] | Prisma.AccountEntryScalarFieldEnum
  having?: Prisma.AccountEntryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccountEntryCountAggregateInputType | true
  _avg?: AccountEntryAvgAggregateInputType
  _sum?: AccountEntrySumAggregateInputType
  _min?: AccountEntryMinAggregateInputType
  _max?: AccountEntryMaxAggregateInputType
}

export type AccountEntryGroupByOutputType = {
  id: number
  accountId: number
  paymentId: number | null
  movementId: number | null
  amount: runtime.Decimal
  entryType: $Enums.EntryType
  description: string
  createdAt: Date
  updatedAt: Date
  _count: AccountEntryCountAggregateOutputType | null
  _avg: AccountEntryAvgAggregateOutputType | null
  _sum: AccountEntrySumAggregateOutputType | null
  _min: AccountEntryMinAggregateOutputType | null
  _max: AccountEntryMaxAggregateOutputType | null
}

type GetAccountEntryGroupByPayload<T extends AccountEntryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccountEntryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccountEntryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccountEntryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccountEntryGroupByOutputType[P]>
      }
    >
  >



export type AccountEntryWhereInput = {
  AND?: Prisma.AccountEntryWhereInput | Prisma.AccountEntryWhereInput[]
  OR?: Prisma.AccountEntryWhereInput[]
  NOT?: Prisma.AccountEntryWhereInput | Prisma.AccountEntryWhereInput[]
  id?: Prisma.IntFilter<"AccountEntry"> | number
  accountId?: Prisma.IntFilter<"AccountEntry"> | number
  paymentId?: Prisma.IntNullableFilter<"AccountEntry"> | number | null
  movementId?: Prisma.IntNullableFilter<"AccountEntry"> | number | null
  amount?: Prisma.DecimalFilter<"AccountEntry"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFilter<"AccountEntry"> | $Enums.EntryType
  description?: Prisma.StringFilter<"AccountEntry"> | string
  createdAt?: Prisma.DateTimeFilter<"AccountEntry"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccountEntry"> | Date | string
  account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>
  payment?: Prisma.XOR<Prisma.PaymentNullableScalarRelationFilter, Prisma.PaymentWhereInput> | null
  movement?: Prisma.XOR<Prisma.MovementNullableScalarRelationFilter, Prisma.MovementWhereInput> | null
}

export type AccountEntryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  paymentId?: Prisma.SortOrderInput | Prisma.SortOrder
  movementId?: Prisma.SortOrderInput | Prisma.SortOrder
  amount?: Prisma.SortOrder
  entryType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  account?: Prisma.AccountOrderByWithRelationInput
  payment?: Prisma.PaymentOrderByWithRelationInput
  movement?: Prisma.MovementOrderByWithRelationInput
}

export type AccountEntryWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.AccountEntryWhereInput | Prisma.AccountEntryWhereInput[]
  OR?: Prisma.AccountEntryWhereInput[]
  NOT?: Prisma.AccountEntryWhereInput | Prisma.AccountEntryWhereInput[]
  accountId?: Prisma.IntFilter<"AccountEntry"> | number
  paymentId?: Prisma.IntNullableFilter<"AccountEntry"> | number | null
  movementId?: Prisma.IntNullableFilter<"AccountEntry"> | number | null
  amount?: Prisma.DecimalFilter<"AccountEntry"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFilter<"AccountEntry"> | $Enums.EntryType
  description?: Prisma.StringFilter<"AccountEntry"> | string
  createdAt?: Prisma.DateTimeFilter<"AccountEntry"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccountEntry"> | Date | string
  account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>
  payment?: Prisma.XOR<Prisma.PaymentNullableScalarRelationFilter, Prisma.PaymentWhereInput> | null
  movement?: Prisma.XOR<Prisma.MovementNullableScalarRelationFilter, Prisma.MovementWhereInput> | null
}, "id">

export type AccountEntryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  paymentId?: Prisma.SortOrderInput | Prisma.SortOrder
  movementId?: Prisma.SortOrderInput | Prisma.SortOrder
  amount?: Prisma.SortOrder
  entryType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AccountEntryCountOrderByAggregateInput
  _avg?: Prisma.AccountEntryAvgOrderByAggregateInput
  _max?: Prisma.AccountEntryMaxOrderByAggregateInput
  _min?: Prisma.AccountEntryMinOrderByAggregateInput
  _sum?: Prisma.AccountEntrySumOrderByAggregateInput
}

export type AccountEntryScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccountEntryScalarWhereWithAggregatesInput | Prisma.AccountEntryScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccountEntryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccountEntryScalarWhereWithAggregatesInput | Prisma.AccountEntryScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"AccountEntry"> | number
  accountId?: Prisma.IntWithAggregatesFilter<"AccountEntry"> | number
  paymentId?: Prisma.IntNullableWithAggregatesFilter<"AccountEntry"> | number | null
  movementId?: Prisma.IntNullableWithAggregatesFilter<"AccountEntry"> | number | null
  amount?: Prisma.DecimalWithAggregatesFilter<"AccountEntry"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeWithAggregatesFilter<"AccountEntry"> | $Enums.EntryType
  description?: Prisma.StringWithAggregatesFilter<"AccountEntry"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AccountEntry"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AccountEntry"> | Date | string
}

export type AccountEntryCreateInput = {
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType: $Enums.EntryType
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
  account: Prisma.AccountCreateNestedOneWithoutEntriesInput
  payment?: Prisma.PaymentCreateNestedOneWithoutAccountEntriesInput
  movement?: Prisma.MovementCreateNestedOneWithoutAccountEntriesInput
}

export type AccountEntryUncheckedCreateInput = {
  id?: number
  accountId: number
  paymentId?: number | null
  movementId?: number | null
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType: $Enums.EntryType
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountEntryUpdateInput = {
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  account?: Prisma.AccountUpdateOneRequiredWithoutEntriesNestedInput
  payment?: Prisma.PaymentUpdateOneWithoutAccountEntriesNestedInput
  movement?: Prisma.MovementUpdateOneWithoutAccountEntriesNestedInput
}

export type AccountEntryUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  accountId?: Prisma.IntFieldUpdateOperationsInput | number
  paymentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  movementId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountEntryCreateManyInput = {
  id?: number
  accountId: number
  paymentId?: number | null
  movementId?: number | null
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType: $Enums.EntryType
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountEntryUpdateManyMutationInput = {
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountEntryUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  accountId?: Prisma.IntFieldUpdateOperationsInput | number
  paymentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  movementId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountEntryListRelationFilter = {
  every?: Prisma.AccountEntryWhereInput
  some?: Prisma.AccountEntryWhereInput
  none?: Prisma.AccountEntryWhereInput
}

export type AccountEntryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AccountEntryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  movementId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  entryType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountEntryAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  movementId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type AccountEntryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  movementId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  entryType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountEntryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  movementId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  entryType?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountEntrySumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  paymentId?: Prisma.SortOrder
  movementId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type AccountEntryCreateNestedManyWithoutMovementInput = {
  create?: Prisma.XOR<Prisma.AccountEntryCreateWithoutMovementInput, Prisma.AccountEntryUncheckedCreateWithoutMovementInput> | Prisma.AccountEntryCreateWithoutMovementInput[] | Prisma.AccountEntryUncheckedCreateWithoutMovementInput[]
  connectOrCreate?: Prisma.AccountEntryCreateOrConnectWithoutMovementInput | Prisma.AccountEntryCreateOrConnectWithoutMovementInput[]
  createMany?: Prisma.AccountEntryCreateManyMovementInputEnvelope
  connect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
}

export type AccountEntryUncheckedCreateNestedManyWithoutMovementInput = {
  create?: Prisma.XOR<Prisma.AccountEntryCreateWithoutMovementInput, Prisma.AccountEntryUncheckedCreateWithoutMovementInput> | Prisma.AccountEntryCreateWithoutMovementInput[] | Prisma.AccountEntryUncheckedCreateWithoutMovementInput[]
  connectOrCreate?: Prisma.AccountEntryCreateOrConnectWithoutMovementInput | Prisma.AccountEntryCreateOrConnectWithoutMovementInput[]
  createMany?: Prisma.AccountEntryCreateManyMovementInputEnvelope
  connect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
}

export type AccountEntryUpdateManyWithoutMovementNestedInput = {
  create?: Prisma.XOR<Prisma.AccountEntryCreateWithoutMovementInput, Prisma.AccountEntryUncheckedCreateWithoutMovementInput> | Prisma.AccountEntryCreateWithoutMovementInput[] | Prisma.AccountEntryUncheckedCreateWithoutMovementInput[]
  connectOrCreate?: Prisma.AccountEntryCreateOrConnectWithoutMovementInput | Prisma.AccountEntryCreateOrConnectWithoutMovementInput[]
  upsert?: Prisma.AccountEntryUpsertWithWhereUniqueWithoutMovementInput | Prisma.AccountEntryUpsertWithWhereUniqueWithoutMovementInput[]
  createMany?: Prisma.AccountEntryCreateManyMovementInputEnvelope
  set?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  disconnect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  delete?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  connect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  update?: Prisma.AccountEntryUpdateWithWhereUniqueWithoutMovementInput | Prisma.AccountEntryUpdateWithWhereUniqueWithoutMovementInput[]
  updateMany?: Prisma.AccountEntryUpdateManyWithWhereWithoutMovementInput | Prisma.AccountEntryUpdateManyWithWhereWithoutMovementInput[]
  deleteMany?: Prisma.AccountEntryScalarWhereInput | Prisma.AccountEntryScalarWhereInput[]
}

export type AccountEntryUncheckedUpdateManyWithoutMovementNestedInput = {
  create?: Prisma.XOR<Prisma.AccountEntryCreateWithoutMovementInput, Prisma.AccountEntryUncheckedCreateWithoutMovementInput> | Prisma.AccountEntryCreateWithoutMovementInput[] | Prisma.AccountEntryUncheckedCreateWithoutMovementInput[]
  connectOrCreate?: Prisma.AccountEntryCreateOrConnectWithoutMovementInput | Prisma.AccountEntryCreateOrConnectWithoutMovementInput[]
  upsert?: Prisma.AccountEntryUpsertWithWhereUniqueWithoutMovementInput | Prisma.AccountEntryUpsertWithWhereUniqueWithoutMovementInput[]
  createMany?: Prisma.AccountEntryCreateManyMovementInputEnvelope
  set?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  disconnect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  delete?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  connect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  update?: Prisma.AccountEntryUpdateWithWhereUniqueWithoutMovementInput | Prisma.AccountEntryUpdateWithWhereUniqueWithoutMovementInput[]
  updateMany?: Prisma.AccountEntryUpdateManyWithWhereWithoutMovementInput | Prisma.AccountEntryUpdateManyWithWhereWithoutMovementInput[]
  deleteMany?: Prisma.AccountEntryScalarWhereInput | Prisma.AccountEntryScalarWhereInput[]
}

export type AccountEntryCreateNestedManyWithoutPaymentInput = {
  create?: Prisma.XOR<Prisma.AccountEntryCreateWithoutPaymentInput, Prisma.AccountEntryUncheckedCreateWithoutPaymentInput> | Prisma.AccountEntryCreateWithoutPaymentInput[] | Prisma.AccountEntryUncheckedCreateWithoutPaymentInput[]
  connectOrCreate?: Prisma.AccountEntryCreateOrConnectWithoutPaymentInput | Prisma.AccountEntryCreateOrConnectWithoutPaymentInput[]
  createMany?: Prisma.AccountEntryCreateManyPaymentInputEnvelope
  connect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
}

export type AccountEntryUncheckedCreateNestedManyWithoutPaymentInput = {
  create?: Prisma.XOR<Prisma.AccountEntryCreateWithoutPaymentInput, Prisma.AccountEntryUncheckedCreateWithoutPaymentInput> | Prisma.AccountEntryCreateWithoutPaymentInput[] | Prisma.AccountEntryUncheckedCreateWithoutPaymentInput[]
  connectOrCreate?: Prisma.AccountEntryCreateOrConnectWithoutPaymentInput | Prisma.AccountEntryCreateOrConnectWithoutPaymentInput[]
  createMany?: Prisma.AccountEntryCreateManyPaymentInputEnvelope
  connect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
}

export type AccountEntryUpdateManyWithoutPaymentNestedInput = {
  create?: Prisma.XOR<Prisma.AccountEntryCreateWithoutPaymentInput, Prisma.AccountEntryUncheckedCreateWithoutPaymentInput> | Prisma.AccountEntryCreateWithoutPaymentInput[] | Prisma.AccountEntryUncheckedCreateWithoutPaymentInput[]
  connectOrCreate?: Prisma.AccountEntryCreateOrConnectWithoutPaymentInput | Prisma.AccountEntryCreateOrConnectWithoutPaymentInput[]
  upsert?: Prisma.AccountEntryUpsertWithWhereUniqueWithoutPaymentInput | Prisma.AccountEntryUpsertWithWhereUniqueWithoutPaymentInput[]
  createMany?: Prisma.AccountEntryCreateManyPaymentInputEnvelope
  set?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  disconnect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  delete?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  connect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  update?: Prisma.AccountEntryUpdateWithWhereUniqueWithoutPaymentInput | Prisma.AccountEntryUpdateWithWhereUniqueWithoutPaymentInput[]
  updateMany?: Prisma.AccountEntryUpdateManyWithWhereWithoutPaymentInput | Prisma.AccountEntryUpdateManyWithWhereWithoutPaymentInput[]
  deleteMany?: Prisma.AccountEntryScalarWhereInput | Prisma.AccountEntryScalarWhereInput[]
}

export type AccountEntryUncheckedUpdateManyWithoutPaymentNestedInput = {
  create?: Prisma.XOR<Prisma.AccountEntryCreateWithoutPaymentInput, Prisma.AccountEntryUncheckedCreateWithoutPaymentInput> | Prisma.AccountEntryCreateWithoutPaymentInput[] | Prisma.AccountEntryUncheckedCreateWithoutPaymentInput[]
  connectOrCreate?: Prisma.AccountEntryCreateOrConnectWithoutPaymentInput | Prisma.AccountEntryCreateOrConnectWithoutPaymentInput[]
  upsert?: Prisma.AccountEntryUpsertWithWhereUniqueWithoutPaymentInput | Prisma.AccountEntryUpsertWithWhereUniqueWithoutPaymentInput[]
  createMany?: Prisma.AccountEntryCreateManyPaymentInputEnvelope
  set?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  disconnect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  delete?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  connect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  update?: Prisma.AccountEntryUpdateWithWhereUniqueWithoutPaymentInput | Prisma.AccountEntryUpdateWithWhereUniqueWithoutPaymentInput[]
  updateMany?: Prisma.AccountEntryUpdateManyWithWhereWithoutPaymentInput | Prisma.AccountEntryUpdateManyWithWhereWithoutPaymentInput[]
  deleteMany?: Prisma.AccountEntryScalarWhereInput | Prisma.AccountEntryScalarWhereInput[]
}

export type AccountEntryCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.AccountEntryCreateWithoutAccountInput, Prisma.AccountEntryUncheckedCreateWithoutAccountInput> | Prisma.AccountEntryCreateWithoutAccountInput[] | Prisma.AccountEntryUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.AccountEntryCreateOrConnectWithoutAccountInput | Prisma.AccountEntryCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.AccountEntryCreateManyAccountInputEnvelope
  connect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
}

export type AccountEntryUncheckedCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.AccountEntryCreateWithoutAccountInput, Prisma.AccountEntryUncheckedCreateWithoutAccountInput> | Prisma.AccountEntryCreateWithoutAccountInput[] | Prisma.AccountEntryUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.AccountEntryCreateOrConnectWithoutAccountInput | Prisma.AccountEntryCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.AccountEntryCreateManyAccountInputEnvelope
  connect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
}

export type AccountEntryUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.AccountEntryCreateWithoutAccountInput, Prisma.AccountEntryUncheckedCreateWithoutAccountInput> | Prisma.AccountEntryCreateWithoutAccountInput[] | Prisma.AccountEntryUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.AccountEntryCreateOrConnectWithoutAccountInput | Prisma.AccountEntryCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.AccountEntryUpsertWithWhereUniqueWithoutAccountInput | Prisma.AccountEntryUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.AccountEntryCreateManyAccountInputEnvelope
  set?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  disconnect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  delete?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  connect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  update?: Prisma.AccountEntryUpdateWithWhereUniqueWithoutAccountInput | Prisma.AccountEntryUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.AccountEntryUpdateManyWithWhereWithoutAccountInput | Prisma.AccountEntryUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.AccountEntryScalarWhereInput | Prisma.AccountEntryScalarWhereInput[]
}

export type AccountEntryUncheckedUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.AccountEntryCreateWithoutAccountInput, Prisma.AccountEntryUncheckedCreateWithoutAccountInput> | Prisma.AccountEntryCreateWithoutAccountInput[] | Prisma.AccountEntryUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.AccountEntryCreateOrConnectWithoutAccountInput | Prisma.AccountEntryCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.AccountEntryUpsertWithWhereUniqueWithoutAccountInput | Prisma.AccountEntryUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.AccountEntryCreateManyAccountInputEnvelope
  set?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  disconnect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  delete?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  connect?: Prisma.AccountEntryWhereUniqueInput | Prisma.AccountEntryWhereUniqueInput[]
  update?: Prisma.AccountEntryUpdateWithWhereUniqueWithoutAccountInput | Prisma.AccountEntryUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.AccountEntryUpdateManyWithWhereWithoutAccountInput | Prisma.AccountEntryUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.AccountEntryScalarWhereInput | Prisma.AccountEntryScalarWhereInput[]
}

export type EnumEntryTypeFieldUpdateOperationsInput = {
  set?: $Enums.EntryType
}

export type AccountEntryCreateWithoutMovementInput = {
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType: $Enums.EntryType
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
  account: Prisma.AccountCreateNestedOneWithoutEntriesInput
  payment?: Prisma.PaymentCreateNestedOneWithoutAccountEntriesInput
}

export type AccountEntryUncheckedCreateWithoutMovementInput = {
  id?: number
  accountId: number
  paymentId?: number | null
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType: $Enums.EntryType
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountEntryCreateOrConnectWithoutMovementInput = {
  where: Prisma.AccountEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountEntryCreateWithoutMovementInput, Prisma.AccountEntryUncheckedCreateWithoutMovementInput>
}

export type AccountEntryCreateManyMovementInputEnvelope = {
  data: Prisma.AccountEntryCreateManyMovementInput | Prisma.AccountEntryCreateManyMovementInput[]
  skipDuplicates?: boolean
}

export type AccountEntryUpsertWithWhereUniqueWithoutMovementInput = {
  where: Prisma.AccountEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.AccountEntryUpdateWithoutMovementInput, Prisma.AccountEntryUncheckedUpdateWithoutMovementInput>
  create: Prisma.XOR<Prisma.AccountEntryCreateWithoutMovementInput, Prisma.AccountEntryUncheckedCreateWithoutMovementInput>
}

export type AccountEntryUpdateWithWhereUniqueWithoutMovementInput = {
  where: Prisma.AccountEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.AccountEntryUpdateWithoutMovementInput, Prisma.AccountEntryUncheckedUpdateWithoutMovementInput>
}

export type AccountEntryUpdateManyWithWhereWithoutMovementInput = {
  where: Prisma.AccountEntryScalarWhereInput
  data: Prisma.XOR<Prisma.AccountEntryUpdateManyMutationInput, Prisma.AccountEntryUncheckedUpdateManyWithoutMovementInput>
}

export type AccountEntryScalarWhereInput = {
  AND?: Prisma.AccountEntryScalarWhereInput | Prisma.AccountEntryScalarWhereInput[]
  OR?: Prisma.AccountEntryScalarWhereInput[]
  NOT?: Prisma.AccountEntryScalarWhereInput | Prisma.AccountEntryScalarWhereInput[]
  id?: Prisma.IntFilter<"AccountEntry"> | number
  accountId?: Prisma.IntFilter<"AccountEntry"> | number
  paymentId?: Prisma.IntNullableFilter<"AccountEntry"> | number | null
  movementId?: Prisma.IntNullableFilter<"AccountEntry"> | number | null
  amount?: Prisma.DecimalFilter<"AccountEntry"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFilter<"AccountEntry"> | $Enums.EntryType
  description?: Prisma.StringFilter<"AccountEntry"> | string
  createdAt?: Prisma.DateTimeFilter<"AccountEntry"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccountEntry"> | Date | string
}

export type AccountEntryCreateWithoutPaymentInput = {
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType: $Enums.EntryType
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
  account: Prisma.AccountCreateNestedOneWithoutEntriesInput
  movement?: Prisma.MovementCreateNestedOneWithoutAccountEntriesInput
}

export type AccountEntryUncheckedCreateWithoutPaymentInput = {
  id?: number
  accountId: number
  movementId?: number | null
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType: $Enums.EntryType
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountEntryCreateOrConnectWithoutPaymentInput = {
  where: Prisma.AccountEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountEntryCreateWithoutPaymentInput, Prisma.AccountEntryUncheckedCreateWithoutPaymentInput>
}

export type AccountEntryCreateManyPaymentInputEnvelope = {
  data: Prisma.AccountEntryCreateManyPaymentInput | Prisma.AccountEntryCreateManyPaymentInput[]
  skipDuplicates?: boolean
}

export type AccountEntryUpsertWithWhereUniqueWithoutPaymentInput = {
  where: Prisma.AccountEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.AccountEntryUpdateWithoutPaymentInput, Prisma.AccountEntryUncheckedUpdateWithoutPaymentInput>
  create: Prisma.XOR<Prisma.AccountEntryCreateWithoutPaymentInput, Prisma.AccountEntryUncheckedCreateWithoutPaymentInput>
}

export type AccountEntryUpdateWithWhereUniqueWithoutPaymentInput = {
  where: Prisma.AccountEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.AccountEntryUpdateWithoutPaymentInput, Prisma.AccountEntryUncheckedUpdateWithoutPaymentInput>
}

export type AccountEntryUpdateManyWithWhereWithoutPaymentInput = {
  where: Prisma.AccountEntryScalarWhereInput
  data: Prisma.XOR<Prisma.AccountEntryUpdateManyMutationInput, Prisma.AccountEntryUncheckedUpdateManyWithoutPaymentInput>
}

export type AccountEntryCreateWithoutAccountInput = {
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType: $Enums.EntryType
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
  payment?: Prisma.PaymentCreateNestedOneWithoutAccountEntriesInput
  movement?: Prisma.MovementCreateNestedOneWithoutAccountEntriesInput
}

export type AccountEntryUncheckedCreateWithoutAccountInput = {
  id?: number
  paymentId?: number | null
  movementId?: number | null
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType: $Enums.EntryType
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountEntryCreateOrConnectWithoutAccountInput = {
  where: Prisma.AccountEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountEntryCreateWithoutAccountInput, Prisma.AccountEntryUncheckedCreateWithoutAccountInput>
}

export type AccountEntryCreateManyAccountInputEnvelope = {
  data: Prisma.AccountEntryCreateManyAccountInput | Prisma.AccountEntryCreateManyAccountInput[]
  skipDuplicates?: boolean
}

export type AccountEntryUpsertWithWhereUniqueWithoutAccountInput = {
  where: Prisma.AccountEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.AccountEntryUpdateWithoutAccountInput, Prisma.AccountEntryUncheckedUpdateWithoutAccountInput>
  create: Prisma.XOR<Prisma.AccountEntryCreateWithoutAccountInput, Prisma.AccountEntryUncheckedCreateWithoutAccountInput>
}

export type AccountEntryUpdateWithWhereUniqueWithoutAccountInput = {
  where: Prisma.AccountEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.AccountEntryUpdateWithoutAccountInput, Prisma.AccountEntryUncheckedUpdateWithoutAccountInput>
}

export type AccountEntryUpdateManyWithWhereWithoutAccountInput = {
  where: Prisma.AccountEntryScalarWhereInput
  data: Prisma.XOR<Prisma.AccountEntryUpdateManyMutationInput, Prisma.AccountEntryUncheckedUpdateManyWithoutAccountInput>
}

export type AccountEntryCreateManyMovementInput = {
  id?: number
  accountId: number
  paymentId?: number | null
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType: $Enums.EntryType
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountEntryUpdateWithoutMovementInput = {
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  account?: Prisma.AccountUpdateOneRequiredWithoutEntriesNestedInput
  payment?: Prisma.PaymentUpdateOneWithoutAccountEntriesNestedInput
}

export type AccountEntryUncheckedUpdateWithoutMovementInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  accountId?: Prisma.IntFieldUpdateOperationsInput | number
  paymentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountEntryUncheckedUpdateManyWithoutMovementInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  accountId?: Prisma.IntFieldUpdateOperationsInput | number
  paymentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountEntryCreateManyPaymentInput = {
  id?: number
  accountId: number
  movementId?: number | null
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType: $Enums.EntryType
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountEntryUpdateWithoutPaymentInput = {
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  account?: Prisma.AccountUpdateOneRequiredWithoutEntriesNestedInput
  movement?: Prisma.MovementUpdateOneWithoutAccountEntriesNestedInput
}

export type AccountEntryUncheckedUpdateWithoutPaymentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  accountId?: Prisma.IntFieldUpdateOperationsInput | number
  movementId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountEntryUncheckedUpdateManyWithoutPaymentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  accountId?: Prisma.IntFieldUpdateOperationsInput | number
  movementId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountEntryCreateManyAccountInput = {
  id?: number
  paymentId?: number | null
  movementId?: number | null
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType: $Enums.EntryType
  description: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountEntryUpdateWithoutAccountInput = {
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payment?: Prisma.PaymentUpdateOneWithoutAccountEntriesNestedInput
  movement?: Prisma.MovementUpdateOneWithoutAccountEntriesNestedInput
}

export type AccountEntryUncheckedUpdateWithoutAccountInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  paymentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  movementId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountEntryUncheckedUpdateManyWithoutAccountInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  paymentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  movementId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  entryType?: Prisma.EnumEntryTypeFieldUpdateOperationsInput | $Enums.EntryType
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AccountEntrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountId?: boolean
  paymentId?: boolean
  movementId?: boolean
  amount?: boolean
  entryType?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  payment?: boolean | Prisma.AccountEntry$paymentArgs<ExtArgs>
  movement?: boolean | Prisma.AccountEntry$movementArgs<ExtArgs>
}, ExtArgs["result"]["accountEntry"]>

export type AccountEntrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountId?: boolean
  paymentId?: boolean
  movementId?: boolean
  amount?: boolean
  entryType?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  payment?: boolean | Prisma.AccountEntry$paymentArgs<ExtArgs>
  movement?: boolean | Prisma.AccountEntry$movementArgs<ExtArgs>
}, ExtArgs["result"]["accountEntry"]>

export type AccountEntrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  accountId?: boolean
  paymentId?: boolean
  movementId?: boolean
  amount?: boolean
  entryType?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  payment?: boolean | Prisma.AccountEntry$paymentArgs<ExtArgs>
  movement?: boolean | Prisma.AccountEntry$movementArgs<ExtArgs>
}, ExtArgs["result"]["accountEntry"]>

export type AccountEntrySelectScalar = {
  id?: boolean
  accountId?: boolean
  paymentId?: boolean
  movementId?: boolean
  amount?: boolean
  entryType?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AccountEntryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "accountId" | "paymentId" | "movementId" | "amount" | "entryType" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["accountEntry"]>
export type AccountEntryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  payment?: boolean | Prisma.AccountEntry$paymentArgs<ExtArgs>
  movement?: boolean | Prisma.AccountEntry$movementArgs<ExtArgs>
}
export type AccountEntryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  payment?: boolean | Prisma.AccountEntry$paymentArgs<ExtArgs>
  movement?: boolean | Prisma.AccountEntry$movementArgs<ExtArgs>
}
export type AccountEntryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.AccountDefaultArgs<ExtArgs>
  payment?: boolean | Prisma.AccountEntry$paymentArgs<ExtArgs>
  movement?: boolean | Prisma.AccountEntry$movementArgs<ExtArgs>
}

export type $AccountEntryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AccountEntry"
  objects: {
    account: Prisma.$AccountPayload<ExtArgs>
    payment: Prisma.$PaymentPayload<ExtArgs> | null
    movement: Prisma.$MovementPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    accountId: number
    paymentId: number | null
    movementId: number | null
    amount: runtime.Decimal
    entryType: $Enums.EntryType
    description: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["accountEntry"]>
  composites: {}
}

export type AccountEntryGetPayload<S extends boolean | null | undefined | AccountEntryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccountEntryPayload, S>

export type AccountEntryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccountEntryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccountEntryCountAggregateInputType | true
  }

export interface AccountEntryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AccountEntry'], meta: { name: 'AccountEntry' } }
  /**
   * Find zero or one AccountEntry that matches the filter.
   * @param {AccountEntryFindUniqueArgs} args - Arguments to find a AccountEntry
   * @example
   * // Get one AccountEntry
   * const accountEntry = await prisma.accountEntry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccountEntryFindUniqueArgs>(args: Prisma.SelectSubset<T, AccountEntryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccountEntryClient<runtime.Types.Result.GetResult<Prisma.$AccountEntryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AccountEntry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccountEntryFindUniqueOrThrowArgs} args - Arguments to find a AccountEntry
   * @example
   * // Get one AccountEntry
   * const accountEntry = await prisma.accountEntry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccountEntryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccountEntryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountEntryClient<runtime.Types.Result.GetResult<Prisma.$AccountEntryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccountEntry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountEntryFindFirstArgs} args - Arguments to find a AccountEntry
   * @example
   * // Get one AccountEntry
   * const accountEntry = await prisma.accountEntry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccountEntryFindFirstArgs>(args?: Prisma.SelectSubset<T, AccountEntryFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccountEntryClient<runtime.Types.Result.GetResult<Prisma.$AccountEntryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccountEntry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountEntryFindFirstOrThrowArgs} args - Arguments to find a AccountEntry
   * @example
   * // Get one AccountEntry
   * const accountEntry = await prisma.accountEntry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccountEntryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccountEntryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountEntryClient<runtime.Types.Result.GetResult<Prisma.$AccountEntryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AccountEntries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountEntryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AccountEntries
   * const accountEntries = await prisma.accountEntry.findMany()
   * 
   * // Get first 10 AccountEntries
   * const accountEntries = await prisma.accountEntry.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accountEntryWithIdOnly = await prisma.accountEntry.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccountEntryFindManyArgs>(args?: Prisma.SelectSubset<T, AccountEntryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AccountEntry.
   * @param {AccountEntryCreateArgs} args - Arguments to create a AccountEntry.
   * @example
   * // Create one AccountEntry
   * const AccountEntry = await prisma.accountEntry.create({
   *   data: {
   *     // ... data to create a AccountEntry
   *   }
   * })
   * 
   */
  create<T extends AccountEntryCreateArgs>(args: Prisma.SelectSubset<T, AccountEntryCreateArgs<ExtArgs>>): Prisma.Prisma__AccountEntryClient<runtime.Types.Result.GetResult<Prisma.$AccountEntryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AccountEntries.
   * @param {AccountEntryCreateManyArgs} args - Arguments to create many AccountEntries.
   * @example
   * // Create many AccountEntries
   * const accountEntry = await prisma.accountEntry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccountEntryCreateManyArgs>(args?: Prisma.SelectSubset<T, AccountEntryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AccountEntries and returns the data saved in the database.
   * @param {AccountEntryCreateManyAndReturnArgs} args - Arguments to create many AccountEntries.
   * @example
   * // Create many AccountEntries
   * const accountEntry = await prisma.accountEntry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AccountEntries and only return the `id`
   * const accountEntryWithIdOnly = await prisma.accountEntry.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccountEntryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccountEntryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountEntryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AccountEntry.
   * @param {AccountEntryDeleteArgs} args - Arguments to delete one AccountEntry.
   * @example
   * // Delete one AccountEntry
   * const AccountEntry = await prisma.accountEntry.delete({
   *   where: {
   *     // ... filter to delete one AccountEntry
   *   }
   * })
   * 
   */
  delete<T extends AccountEntryDeleteArgs>(args: Prisma.SelectSubset<T, AccountEntryDeleteArgs<ExtArgs>>): Prisma.Prisma__AccountEntryClient<runtime.Types.Result.GetResult<Prisma.$AccountEntryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AccountEntry.
   * @param {AccountEntryUpdateArgs} args - Arguments to update one AccountEntry.
   * @example
   * // Update one AccountEntry
   * const accountEntry = await prisma.accountEntry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccountEntryUpdateArgs>(args: Prisma.SelectSubset<T, AccountEntryUpdateArgs<ExtArgs>>): Prisma.Prisma__AccountEntryClient<runtime.Types.Result.GetResult<Prisma.$AccountEntryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AccountEntries.
   * @param {AccountEntryDeleteManyArgs} args - Arguments to filter AccountEntries to delete.
   * @example
   * // Delete a few AccountEntries
   * const { count } = await prisma.accountEntry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccountEntryDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccountEntryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccountEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountEntryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AccountEntries
   * const accountEntry = await prisma.accountEntry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccountEntryUpdateManyArgs>(args: Prisma.SelectSubset<T, AccountEntryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccountEntries and returns the data updated in the database.
   * @param {AccountEntryUpdateManyAndReturnArgs} args - Arguments to update many AccountEntries.
   * @example
   * // Update many AccountEntries
   * const accountEntry = await prisma.accountEntry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AccountEntries and only return the `id`
   * const accountEntryWithIdOnly = await prisma.accountEntry.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccountEntryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccountEntryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountEntryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AccountEntry.
   * @param {AccountEntryUpsertArgs} args - Arguments to update or create a AccountEntry.
   * @example
   * // Update or create a AccountEntry
   * const accountEntry = await prisma.accountEntry.upsert({
   *   create: {
   *     // ... data to create a AccountEntry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AccountEntry we want to update
   *   }
   * })
   */
  upsert<T extends AccountEntryUpsertArgs>(args: Prisma.SelectSubset<T, AccountEntryUpsertArgs<ExtArgs>>): Prisma.Prisma__AccountEntryClient<runtime.Types.Result.GetResult<Prisma.$AccountEntryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AccountEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountEntryCountArgs} args - Arguments to filter AccountEntries to count.
   * @example
   * // Count the number of AccountEntries
   * const count = await prisma.accountEntry.count({
   *   where: {
   *     // ... the filter for the AccountEntries we want to count
   *   }
   * })
  **/
  count<T extends AccountEntryCountArgs>(
    args?: Prisma.Subset<T, AccountEntryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccountEntryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AccountEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountEntryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccountEntryAggregateArgs>(args: Prisma.Subset<T, AccountEntryAggregateArgs>): Prisma.PrismaPromise<GetAccountEntryAggregateType<T>>

  /**
   * Group by AccountEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountEntryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccountEntryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccountEntryGroupByArgs['orderBy'] }
      : { orderBy?: AccountEntryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccountEntryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccountEntryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AccountEntry model
 */
readonly fields: AccountEntryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AccountEntry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccountEntryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  account<T extends Prisma.AccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccountDefaultArgs<ExtArgs>>): Prisma.Prisma__AccountClient<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  payment<T extends Prisma.AccountEntry$paymentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccountEntry$paymentArgs<ExtArgs>>): Prisma.Prisma__PaymentClient<runtime.Types.Result.GetResult<Prisma.$PaymentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  movement<T extends Prisma.AccountEntry$movementArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccountEntry$movementArgs<ExtArgs>>): Prisma.Prisma__MovementClient<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AccountEntry model
 */
export interface AccountEntryFieldRefs {
  readonly id: Prisma.FieldRef<"AccountEntry", 'Int'>
  readonly accountId: Prisma.FieldRef<"AccountEntry", 'Int'>
  readonly paymentId: Prisma.FieldRef<"AccountEntry", 'Int'>
  readonly movementId: Prisma.FieldRef<"AccountEntry", 'Int'>
  readonly amount: Prisma.FieldRef<"AccountEntry", 'Decimal'>
  readonly entryType: Prisma.FieldRef<"AccountEntry", 'EntryType'>
  readonly description: Prisma.FieldRef<"AccountEntry", 'String'>
  readonly createdAt: Prisma.FieldRef<"AccountEntry", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AccountEntry", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AccountEntry findUnique
 */
export type AccountEntryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountEntry
   */
  select?: Prisma.AccountEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountEntry
   */
  omit?: Prisma.AccountEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountEntryInclude<ExtArgs> | null
  /**
   * Filter, which AccountEntry to fetch.
   */
  where: Prisma.AccountEntryWhereUniqueInput
}

/**
 * AccountEntry findUniqueOrThrow
 */
export type AccountEntryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountEntry
   */
  select?: Prisma.AccountEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountEntry
   */
  omit?: Prisma.AccountEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountEntryInclude<ExtArgs> | null
  /**
   * Filter, which AccountEntry to fetch.
   */
  where: Prisma.AccountEntryWhereUniqueInput
}

/**
 * AccountEntry findFirst
 */
export type AccountEntryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountEntry
   */
  select?: Prisma.AccountEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountEntry
   */
  omit?: Prisma.AccountEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountEntryInclude<ExtArgs> | null
  /**
   * Filter, which AccountEntry to fetch.
   */
  where?: Prisma.AccountEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountEntries to fetch.
   */
  orderBy?: Prisma.AccountEntryOrderByWithRelationInput | Prisma.AccountEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccountEntries.
   */
  cursor?: Prisma.AccountEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountEntries.
   */
  distinct?: Prisma.AccountEntryScalarFieldEnum | Prisma.AccountEntryScalarFieldEnum[]
}

/**
 * AccountEntry findFirstOrThrow
 */
export type AccountEntryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountEntry
   */
  select?: Prisma.AccountEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountEntry
   */
  omit?: Prisma.AccountEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountEntryInclude<ExtArgs> | null
  /**
   * Filter, which AccountEntry to fetch.
   */
  where?: Prisma.AccountEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountEntries to fetch.
   */
  orderBy?: Prisma.AccountEntryOrderByWithRelationInput | Prisma.AccountEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccountEntries.
   */
  cursor?: Prisma.AccountEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountEntries.
   */
  distinct?: Prisma.AccountEntryScalarFieldEnum | Prisma.AccountEntryScalarFieldEnum[]
}

/**
 * AccountEntry findMany
 */
export type AccountEntryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountEntry
   */
  select?: Prisma.AccountEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountEntry
   */
  omit?: Prisma.AccountEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountEntryInclude<ExtArgs> | null
  /**
   * Filter, which AccountEntries to fetch.
   */
  where?: Prisma.AccountEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountEntries to fetch.
   */
  orderBy?: Prisma.AccountEntryOrderByWithRelationInput | Prisma.AccountEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AccountEntries.
   */
  cursor?: Prisma.AccountEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountEntries.
   */
  skip?: number
  distinct?: Prisma.AccountEntryScalarFieldEnum | Prisma.AccountEntryScalarFieldEnum[]
}

/**
 * AccountEntry create
 */
export type AccountEntryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountEntry
   */
  select?: Prisma.AccountEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountEntry
   */
  omit?: Prisma.AccountEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountEntryInclude<ExtArgs> | null
  /**
   * The data needed to create a AccountEntry.
   */
  data: Prisma.XOR<Prisma.AccountEntryCreateInput, Prisma.AccountEntryUncheckedCreateInput>
}

/**
 * AccountEntry createMany
 */
export type AccountEntryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AccountEntries.
   */
  data: Prisma.AccountEntryCreateManyInput | Prisma.AccountEntryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccountEntry createManyAndReturn
 */
export type AccountEntryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountEntry
   */
  select?: Prisma.AccountEntrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccountEntry
   */
  omit?: Prisma.AccountEntryOmit<ExtArgs> | null
  /**
   * The data used to create many AccountEntries.
   */
  data: Prisma.AccountEntryCreateManyInput | Prisma.AccountEntryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountEntryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AccountEntry update
 */
export type AccountEntryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountEntry
   */
  select?: Prisma.AccountEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountEntry
   */
  omit?: Prisma.AccountEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountEntryInclude<ExtArgs> | null
  /**
   * The data needed to update a AccountEntry.
   */
  data: Prisma.XOR<Prisma.AccountEntryUpdateInput, Prisma.AccountEntryUncheckedUpdateInput>
  /**
   * Choose, which AccountEntry to update.
   */
  where: Prisma.AccountEntryWhereUniqueInput
}

/**
 * AccountEntry updateMany
 */
export type AccountEntryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AccountEntries.
   */
  data: Prisma.XOR<Prisma.AccountEntryUpdateManyMutationInput, Prisma.AccountEntryUncheckedUpdateManyInput>
  /**
   * Filter which AccountEntries to update
   */
  where?: Prisma.AccountEntryWhereInput
  /**
   * Limit how many AccountEntries to update.
   */
  limit?: number
}

/**
 * AccountEntry updateManyAndReturn
 */
export type AccountEntryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountEntry
   */
  select?: Prisma.AccountEntrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccountEntry
   */
  omit?: Prisma.AccountEntryOmit<ExtArgs> | null
  /**
   * The data used to update AccountEntries.
   */
  data: Prisma.XOR<Prisma.AccountEntryUpdateManyMutationInput, Prisma.AccountEntryUncheckedUpdateManyInput>
  /**
   * Filter which AccountEntries to update
   */
  where?: Prisma.AccountEntryWhereInput
  /**
   * Limit how many AccountEntries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountEntryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AccountEntry upsert
 */
export type AccountEntryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountEntry
   */
  select?: Prisma.AccountEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountEntry
   */
  omit?: Prisma.AccountEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountEntryInclude<ExtArgs> | null
  /**
   * The filter to search for the AccountEntry to update in case it exists.
   */
  where: Prisma.AccountEntryWhereUniqueInput
  /**
   * In case the AccountEntry found by the `where` argument doesn't exist, create a new AccountEntry with this data.
   */
  create: Prisma.XOR<Prisma.AccountEntryCreateInput, Prisma.AccountEntryUncheckedCreateInput>
  /**
   * In case the AccountEntry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccountEntryUpdateInput, Prisma.AccountEntryUncheckedUpdateInput>
}

/**
 * AccountEntry delete
 */
export type AccountEntryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountEntry
   */
  select?: Prisma.AccountEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountEntry
   */
  omit?: Prisma.AccountEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountEntryInclude<ExtArgs> | null
  /**
   * Filter which AccountEntry to delete.
   */
  where: Prisma.AccountEntryWhereUniqueInput
}

/**
 * AccountEntry deleteMany
 */
export type AccountEntryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccountEntries to delete
   */
  where?: Prisma.AccountEntryWhereInput
  /**
   * Limit how many AccountEntries to delete.
   */
  limit?: number
}

/**
 * AccountEntry.payment
 */
export type AccountEntry$paymentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Payment
   */
  select?: Prisma.PaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Payment
   */
  omit?: Prisma.PaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentInclude<ExtArgs> | null
  where?: Prisma.PaymentWhereInput
}

/**
 * AccountEntry.movement
 */
export type AccountEntry$movementArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementInclude<ExtArgs> | null
  where?: Prisma.MovementWhereInput
}

/**
 * AccountEntry without action
 */
export type AccountEntryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountEntry
   */
  select?: Prisma.AccountEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountEntry
   */
  omit?: Prisma.AccountEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountEntryInclude<ExtArgs> | null
}
