
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MovementLine` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MovementLine
 * 
 */
export type MovementLineModel = runtime.Types.Result.DefaultSelection<Prisma.$MovementLinePayload>

export type AggregateMovementLine = {
  _count: MovementLineCountAggregateOutputType | null
  _avg: MovementLineAvgAggregateOutputType | null
  _sum: MovementLineSumAggregateOutputType | null
  _min: MovementLineMinAggregateOutputType | null
  _max: MovementLineMaxAggregateOutputType | null
}

export type MovementLineAvgAggregateOutputType = {
  id: number | null
  movementId: number | null
  productId: number | null
  quantity: number | null
  unitPrice: runtime.Decimal | null
  subtotal: runtime.Decimal | null
}

export type MovementLineSumAggregateOutputType = {
  id: number | null
  movementId: number | null
  productId: number | null
  quantity: number | null
  unitPrice: runtime.Decimal | null
  subtotal: runtime.Decimal | null
}

export type MovementLineMinAggregateOutputType = {
  id: number | null
  movementId: number | null
  productId: number | null
  quantity: number | null
  unitPrice: runtime.Decimal | null
  subtotal: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MovementLineMaxAggregateOutputType = {
  id: number | null
  movementId: number | null
  productId: number | null
  quantity: number | null
  unitPrice: runtime.Decimal | null
  subtotal: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MovementLineCountAggregateOutputType = {
  id: number
  movementId: number
  productId: number
  quantity: number
  unitPrice: number
  subtotal: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MovementLineAvgAggregateInputType = {
  id?: true
  movementId?: true
  productId?: true
  quantity?: true
  unitPrice?: true
  subtotal?: true
}

export type MovementLineSumAggregateInputType = {
  id?: true
  movementId?: true
  productId?: true
  quantity?: true
  unitPrice?: true
  subtotal?: true
}

export type MovementLineMinAggregateInputType = {
  id?: true
  movementId?: true
  productId?: true
  quantity?: true
  unitPrice?: true
  subtotal?: true
  createdAt?: true
  updatedAt?: true
}

export type MovementLineMaxAggregateInputType = {
  id?: true
  movementId?: true
  productId?: true
  quantity?: true
  unitPrice?: true
  subtotal?: true
  createdAt?: true
  updatedAt?: true
}

export type MovementLineCountAggregateInputType = {
  id?: true
  movementId?: true
  productId?: true
  quantity?: true
  unitPrice?: true
  subtotal?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MovementLineAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MovementLine to aggregate.
   */
  where?: Prisma.MovementLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MovementLines to fetch.
   */
  orderBy?: Prisma.MovementLineOrderByWithRelationInput | Prisma.MovementLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MovementLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MovementLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MovementLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MovementLines
  **/
  _count?: true | MovementLineCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MovementLineAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MovementLineSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MovementLineMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MovementLineMaxAggregateInputType
}

export type GetMovementLineAggregateType<T extends MovementLineAggregateArgs> = {
      [P in keyof T & keyof AggregateMovementLine]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMovementLine[P]>
    : Prisma.GetScalarType<T[P], AggregateMovementLine[P]>
}




export type MovementLineGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MovementLineWhereInput
  orderBy?: Prisma.MovementLineOrderByWithAggregationInput | Prisma.MovementLineOrderByWithAggregationInput[]
  by: Prisma.MovementLineScalarFieldEnum[] | Prisma.MovementLineScalarFieldEnum
  having?: Prisma.MovementLineScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MovementLineCountAggregateInputType | true
  _avg?: MovementLineAvgAggregateInputType
  _sum?: MovementLineSumAggregateInputType
  _min?: MovementLineMinAggregateInputType
  _max?: MovementLineMaxAggregateInputType
}

export type MovementLineGroupByOutputType = {
  id: number
  movementId: number
  productId: number
  quantity: number
  unitPrice: runtime.Decimal | null
  subtotal: runtime.Decimal
  createdAt: Date
  updatedAt: Date
  _count: MovementLineCountAggregateOutputType | null
  _avg: MovementLineAvgAggregateOutputType | null
  _sum: MovementLineSumAggregateOutputType | null
  _min: MovementLineMinAggregateOutputType | null
  _max: MovementLineMaxAggregateOutputType | null
}

type GetMovementLineGroupByPayload<T extends MovementLineGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MovementLineGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MovementLineGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MovementLineGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MovementLineGroupByOutputType[P]>
      }
    >
  >



export type MovementLineWhereInput = {
  AND?: Prisma.MovementLineWhereInput | Prisma.MovementLineWhereInput[]
  OR?: Prisma.MovementLineWhereInput[]
  NOT?: Prisma.MovementLineWhereInput | Prisma.MovementLineWhereInput[]
  id?: Prisma.IntFilter<"MovementLine"> | number
  movementId?: Prisma.IntFilter<"MovementLine"> | number
  productId?: Prisma.IntFilter<"MovementLine"> | number
  quantity?: Prisma.IntFilter<"MovementLine"> | number
  unitPrice?: Prisma.DecimalNullableFilter<"MovementLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFilter<"MovementLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"MovementLine"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MovementLine"> | Date | string
  movement?: Prisma.XOR<Prisma.MovementScalarRelationFilter, Prisma.MovementWhereInput>
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type MovementLineOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  movementId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  movement?: Prisma.MovementOrderByWithRelationInput
  product?: Prisma.ProductOrderByWithRelationInput
}

export type MovementLineWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MovementLineWhereInput | Prisma.MovementLineWhereInput[]
  OR?: Prisma.MovementLineWhereInput[]
  NOT?: Prisma.MovementLineWhereInput | Prisma.MovementLineWhereInput[]
  movementId?: Prisma.IntFilter<"MovementLine"> | number
  productId?: Prisma.IntFilter<"MovementLine"> | number
  quantity?: Prisma.IntFilter<"MovementLine"> | number
  unitPrice?: Prisma.DecimalNullableFilter<"MovementLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFilter<"MovementLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"MovementLine"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MovementLine"> | Date | string
  movement?: Prisma.XOR<Prisma.MovementScalarRelationFilter, Prisma.MovementWhereInput>
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id">

export type MovementLineOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  movementId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MovementLineCountOrderByAggregateInput
  _avg?: Prisma.MovementLineAvgOrderByAggregateInput
  _max?: Prisma.MovementLineMaxOrderByAggregateInput
  _min?: Prisma.MovementLineMinOrderByAggregateInput
  _sum?: Prisma.MovementLineSumOrderByAggregateInput
}

export type MovementLineScalarWhereWithAggregatesInput = {
  AND?: Prisma.MovementLineScalarWhereWithAggregatesInput | Prisma.MovementLineScalarWhereWithAggregatesInput[]
  OR?: Prisma.MovementLineScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MovementLineScalarWhereWithAggregatesInput | Prisma.MovementLineScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"MovementLine"> | number
  movementId?: Prisma.IntWithAggregatesFilter<"MovementLine"> | number
  productId?: Prisma.IntWithAggregatesFilter<"MovementLine"> | number
  quantity?: Prisma.IntWithAggregatesFilter<"MovementLine"> | number
  unitPrice?: Prisma.DecimalNullableWithAggregatesFilter<"MovementLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalWithAggregatesFilter<"MovementLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MovementLine"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MovementLine"> | Date | string
}

export type MovementLineCreateInput = {
  quantity: number
  unitPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  movement: Prisma.MovementCreateNestedOneWithoutLinesInput
  product: Prisma.ProductCreateNestedOneWithoutMovementLinesInput
}

export type MovementLineUncheckedCreateInput = {
  id?: number
  movementId: number
  productId: number
  quantity: number
  unitPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MovementLineUpdateInput = {
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  movement?: Prisma.MovementUpdateOneRequiredWithoutLinesNestedInput
  product?: Prisma.ProductUpdateOneRequiredWithoutMovementLinesNestedInput
}

export type MovementLineUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementId?: Prisma.IntFieldUpdateOperationsInput | number
  productId?: Prisma.IntFieldUpdateOperationsInput | number
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MovementLineCreateManyInput = {
  id?: number
  movementId: number
  productId: number
  quantity: number
  unitPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MovementLineUpdateManyMutationInput = {
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MovementLineUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementId?: Prisma.IntFieldUpdateOperationsInput | number
  productId?: Prisma.IntFieldUpdateOperationsInput | number
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MovementLineListRelationFilter = {
  every?: Prisma.MovementLineWhereInput
  some?: Prisma.MovementLineWhereInput
  none?: Prisma.MovementLineWhereInput
}

export type MovementLineOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MovementLineCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  movementId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MovementLineAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  movementId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
}

export type MovementLineMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  movementId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MovementLineMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  movementId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MovementLineSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  movementId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
}

export type MovementLineCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.MovementLineCreateWithoutProductInput, Prisma.MovementLineUncheckedCreateWithoutProductInput> | Prisma.MovementLineCreateWithoutProductInput[] | Prisma.MovementLineUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.MovementLineCreateOrConnectWithoutProductInput | Prisma.MovementLineCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.MovementLineCreateManyProductInputEnvelope
  connect?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
}

export type MovementLineUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.MovementLineCreateWithoutProductInput, Prisma.MovementLineUncheckedCreateWithoutProductInput> | Prisma.MovementLineCreateWithoutProductInput[] | Prisma.MovementLineUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.MovementLineCreateOrConnectWithoutProductInput | Prisma.MovementLineCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.MovementLineCreateManyProductInputEnvelope
  connect?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
}

export type MovementLineUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.MovementLineCreateWithoutProductInput, Prisma.MovementLineUncheckedCreateWithoutProductInput> | Prisma.MovementLineCreateWithoutProductInput[] | Prisma.MovementLineUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.MovementLineCreateOrConnectWithoutProductInput | Prisma.MovementLineCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.MovementLineUpsertWithWhereUniqueWithoutProductInput | Prisma.MovementLineUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.MovementLineCreateManyProductInputEnvelope
  set?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  disconnect?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  delete?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  connect?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  update?: Prisma.MovementLineUpdateWithWhereUniqueWithoutProductInput | Prisma.MovementLineUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.MovementLineUpdateManyWithWhereWithoutProductInput | Prisma.MovementLineUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.MovementLineScalarWhereInput | Prisma.MovementLineScalarWhereInput[]
}

export type MovementLineUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.MovementLineCreateWithoutProductInput, Prisma.MovementLineUncheckedCreateWithoutProductInput> | Prisma.MovementLineCreateWithoutProductInput[] | Prisma.MovementLineUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.MovementLineCreateOrConnectWithoutProductInput | Prisma.MovementLineCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.MovementLineUpsertWithWhereUniqueWithoutProductInput | Prisma.MovementLineUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.MovementLineCreateManyProductInputEnvelope
  set?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  disconnect?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  delete?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  connect?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  update?: Prisma.MovementLineUpdateWithWhereUniqueWithoutProductInput | Prisma.MovementLineUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.MovementLineUpdateManyWithWhereWithoutProductInput | Prisma.MovementLineUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.MovementLineScalarWhereInput | Prisma.MovementLineScalarWhereInput[]
}

export type MovementLineCreateNestedManyWithoutMovementInput = {
  create?: Prisma.XOR<Prisma.MovementLineCreateWithoutMovementInput, Prisma.MovementLineUncheckedCreateWithoutMovementInput> | Prisma.MovementLineCreateWithoutMovementInput[] | Prisma.MovementLineUncheckedCreateWithoutMovementInput[]
  connectOrCreate?: Prisma.MovementLineCreateOrConnectWithoutMovementInput | Prisma.MovementLineCreateOrConnectWithoutMovementInput[]
  createMany?: Prisma.MovementLineCreateManyMovementInputEnvelope
  connect?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
}

export type MovementLineUncheckedCreateNestedManyWithoutMovementInput = {
  create?: Prisma.XOR<Prisma.MovementLineCreateWithoutMovementInput, Prisma.MovementLineUncheckedCreateWithoutMovementInput> | Prisma.MovementLineCreateWithoutMovementInput[] | Prisma.MovementLineUncheckedCreateWithoutMovementInput[]
  connectOrCreate?: Prisma.MovementLineCreateOrConnectWithoutMovementInput | Prisma.MovementLineCreateOrConnectWithoutMovementInput[]
  createMany?: Prisma.MovementLineCreateManyMovementInputEnvelope
  connect?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
}

export type MovementLineUpdateManyWithoutMovementNestedInput = {
  create?: Prisma.XOR<Prisma.MovementLineCreateWithoutMovementInput, Prisma.MovementLineUncheckedCreateWithoutMovementInput> | Prisma.MovementLineCreateWithoutMovementInput[] | Prisma.MovementLineUncheckedCreateWithoutMovementInput[]
  connectOrCreate?: Prisma.MovementLineCreateOrConnectWithoutMovementInput | Prisma.MovementLineCreateOrConnectWithoutMovementInput[]
  upsert?: Prisma.MovementLineUpsertWithWhereUniqueWithoutMovementInput | Prisma.MovementLineUpsertWithWhereUniqueWithoutMovementInput[]
  createMany?: Prisma.MovementLineCreateManyMovementInputEnvelope
  set?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  disconnect?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  delete?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  connect?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  update?: Prisma.MovementLineUpdateWithWhereUniqueWithoutMovementInput | Prisma.MovementLineUpdateWithWhereUniqueWithoutMovementInput[]
  updateMany?: Prisma.MovementLineUpdateManyWithWhereWithoutMovementInput | Prisma.MovementLineUpdateManyWithWhereWithoutMovementInput[]
  deleteMany?: Prisma.MovementLineScalarWhereInput | Prisma.MovementLineScalarWhereInput[]
}

export type MovementLineUncheckedUpdateManyWithoutMovementNestedInput = {
  create?: Prisma.XOR<Prisma.MovementLineCreateWithoutMovementInput, Prisma.MovementLineUncheckedCreateWithoutMovementInput> | Prisma.MovementLineCreateWithoutMovementInput[] | Prisma.MovementLineUncheckedCreateWithoutMovementInput[]
  connectOrCreate?: Prisma.MovementLineCreateOrConnectWithoutMovementInput | Prisma.MovementLineCreateOrConnectWithoutMovementInput[]
  upsert?: Prisma.MovementLineUpsertWithWhereUniqueWithoutMovementInput | Prisma.MovementLineUpsertWithWhereUniqueWithoutMovementInput[]
  createMany?: Prisma.MovementLineCreateManyMovementInputEnvelope
  set?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  disconnect?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  delete?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  connect?: Prisma.MovementLineWhereUniqueInput | Prisma.MovementLineWhereUniqueInput[]
  update?: Prisma.MovementLineUpdateWithWhereUniqueWithoutMovementInput | Prisma.MovementLineUpdateWithWhereUniqueWithoutMovementInput[]
  updateMany?: Prisma.MovementLineUpdateManyWithWhereWithoutMovementInput | Prisma.MovementLineUpdateManyWithWhereWithoutMovementInput[]
  deleteMany?: Prisma.MovementLineScalarWhereInput | Prisma.MovementLineScalarWhereInput[]
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type MovementLineCreateWithoutProductInput = {
  quantity: number
  unitPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  movement: Prisma.MovementCreateNestedOneWithoutLinesInput
}

export type MovementLineUncheckedCreateWithoutProductInput = {
  id?: number
  movementId: number
  quantity: number
  unitPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MovementLineCreateOrConnectWithoutProductInput = {
  where: Prisma.MovementLineWhereUniqueInput
  create: Prisma.XOR<Prisma.MovementLineCreateWithoutProductInput, Prisma.MovementLineUncheckedCreateWithoutProductInput>
}

export type MovementLineCreateManyProductInputEnvelope = {
  data: Prisma.MovementLineCreateManyProductInput | Prisma.MovementLineCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type MovementLineUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.MovementLineWhereUniqueInput
  update: Prisma.XOR<Prisma.MovementLineUpdateWithoutProductInput, Prisma.MovementLineUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.MovementLineCreateWithoutProductInput, Prisma.MovementLineUncheckedCreateWithoutProductInput>
}

export type MovementLineUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.MovementLineWhereUniqueInput
  data: Prisma.XOR<Prisma.MovementLineUpdateWithoutProductInput, Prisma.MovementLineUncheckedUpdateWithoutProductInput>
}

export type MovementLineUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.MovementLineScalarWhereInput
  data: Prisma.XOR<Prisma.MovementLineUpdateManyMutationInput, Prisma.MovementLineUncheckedUpdateManyWithoutProductInput>
}

export type MovementLineScalarWhereInput = {
  AND?: Prisma.MovementLineScalarWhereInput | Prisma.MovementLineScalarWhereInput[]
  OR?: Prisma.MovementLineScalarWhereInput[]
  NOT?: Prisma.MovementLineScalarWhereInput | Prisma.MovementLineScalarWhereInput[]
  id?: Prisma.IntFilter<"MovementLine"> | number
  movementId?: Prisma.IntFilter<"MovementLine"> | number
  productId?: Prisma.IntFilter<"MovementLine"> | number
  quantity?: Prisma.IntFilter<"MovementLine"> | number
  unitPrice?: Prisma.DecimalNullableFilter<"MovementLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFilter<"MovementLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"MovementLine"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MovementLine"> | Date | string
}

export type MovementLineCreateWithoutMovementInput = {
  quantity: number
  unitPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  product: Prisma.ProductCreateNestedOneWithoutMovementLinesInput
}

export type MovementLineUncheckedCreateWithoutMovementInput = {
  id?: number
  productId: number
  quantity: number
  unitPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MovementLineCreateOrConnectWithoutMovementInput = {
  where: Prisma.MovementLineWhereUniqueInput
  create: Prisma.XOR<Prisma.MovementLineCreateWithoutMovementInput, Prisma.MovementLineUncheckedCreateWithoutMovementInput>
}

export type MovementLineCreateManyMovementInputEnvelope = {
  data: Prisma.MovementLineCreateManyMovementInput | Prisma.MovementLineCreateManyMovementInput[]
  skipDuplicates?: boolean
}

export type MovementLineUpsertWithWhereUniqueWithoutMovementInput = {
  where: Prisma.MovementLineWhereUniqueInput
  update: Prisma.XOR<Prisma.MovementLineUpdateWithoutMovementInput, Prisma.MovementLineUncheckedUpdateWithoutMovementInput>
  create: Prisma.XOR<Prisma.MovementLineCreateWithoutMovementInput, Prisma.MovementLineUncheckedCreateWithoutMovementInput>
}

export type MovementLineUpdateWithWhereUniqueWithoutMovementInput = {
  where: Prisma.MovementLineWhereUniqueInput
  data: Prisma.XOR<Prisma.MovementLineUpdateWithoutMovementInput, Prisma.MovementLineUncheckedUpdateWithoutMovementInput>
}

export type MovementLineUpdateManyWithWhereWithoutMovementInput = {
  where: Prisma.MovementLineScalarWhereInput
  data: Prisma.XOR<Prisma.MovementLineUpdateManyMutationInput, Prisma.MovementLineUncheckedUpdateManyWithoutMovementInput>
}

export type MovementLineCreateManyProductInput = {
  id?: number
  movementId: number
  quantity: number
  unitPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MovementLineUpdateWithoutProductInput = {
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  movement?: Prisma.MovementUpdateOneRequiredWithoutLinesNestedInput
}

export type MovementLineUncheckedUpdateWithoutProductInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementId?: Prisma.IntFieldUpdateOperationsInput | number
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MovementLineUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementId?: Prisma.IntFieldUpdateOperationsInput | number
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MovementLineCreateManyMovementInput = {
  id?: number
  productId: number
  quantity: number
  unitPrice?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MovementLineUpdateWithoutMovementInput = {
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  product?: Prisma.ProductUpdateOneRequiredWithoutMovementLinesNestedInput
}

export type MovementLineUncheckedUpdateWithoutMovementInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  productId?: Prisma.IntFieldUpdateOperationsInput | number
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MovementLineUncheckedUpdateManyWithoutMovementInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  productId?: Prisma.IntFieldUpdateOperationsInput | number
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  subtotal?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MovementLineSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  movementId?: boolean
  productId?: boolean
  quantity?: boolean
  unitPrice?: boolean
  subtotal?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  movement?: boolean | Prisma.MovementDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["movementLine"]>

export type MovementLineSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  movementId?: boolean
  productId?: boolean
  quantity?: boolean
  unitPrice?: boolean
  subtotal?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  movement?: boolean | Prisma.MovementDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["movementLine"]>

export type MovementLineSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  movementId?: boolean
  productId?: boolean
  quantity?: boolean
  unitPrice?: boolean
  subtotal?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  movement?: boolean | Prisma.MovementDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["movementLine"]>

export type MovementLineSelectScalar = {
  id?: boolean
  movementId?: boolean
  productId?: boolean
  quantity?: boolean
  unitPrice?: boolean
  subtotal?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MovementLineOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "movementId" | "productId" | "quantity" | "unitPrice" | "subtotal" | "createdAt" | "updatedAt", ExtArgs["result"]["movementLine"]>
export type MovementLineInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  movement?: boolean | Prisma.MovementDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type MovementLineIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  movement?: boolean | Prisma.MovementDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type MovementLineIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  movement?: boolean | Prisma.MovementDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $MovementLinePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MovementLine"
  objects: {
    movement: Prisma.$MovementPayload<ExtArgs>
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    movementId: number
    productId: number
    quantity: number
    unitPrice: runtime.Decimal | null
    subtotal: runtime.Decimal
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["movementLine"]>
  composites: {}
}

export type MovementLineGetPayload<S extends boolean | null | undefined | MovementLineDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MovementLinePayload, S>

export type MovementLineCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MovementLineFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MovementLineCountAggregateInputType | true
  }

export interface MovementLineDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MovementLine'], meta: { name: 'MovementLine' } }
  /**
   * Find zero or one MovementLine that matches the filter.
   * @param {MovementLineFindUniqueArgs} args - Arguments to find a MovementLine
   * @example
   * // Get one MovementLine
   * const movementLine = await prisma.movementLine.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MovementLineFindUniqueArgs>(args: Prisma.SelectSubset<T, MovementLineFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MovementLineClient<runtime.Types.Result.GetResult<Prisma.$MovementLinePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MovementLine that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MovementLineFindUniqueOrThrowArgs} args - Arguments to find a MovementLine
   * @example
   * // Get one MovementLine
   * const movementLine = await prisma.movementLine.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MovementLineFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MovementLineFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MovementLineClient<runtime.Types.Result.GetResult<Prisma.$MovementLinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MovementLine that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementLineFindFirstArgs} args - Arguments to find a MovementLine
   * @example
   * // Get one MovementLine
   * const movementLine = await prisma.movementLine.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MovementLineFindFirstArgs>(args?: Prisma.SelectSubset<T, MovementLineFindFirstArgs<ExtArgs>>): Prisma.Prisma__MovementLineClient<runtime.Types.Result.GetResult<Prisma.$MovementLinePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MovementLine that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementLineFindFirstOrThrowArgs} args - Arguments to find a MovementLine
   * @example
   * // Get one MovementLine
   * const movementLine = await prisma.movementLine.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MovementLineFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MovementLineFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MovementLineClient<runtime.Types.Result.GetResult<Prisma.$MovementLinePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MovementLines that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementLineFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MovementLines
   * const movementLines = await prisma.movementLine.findMany()
   * 
   * // Get first 10 MovementLines
   * const movementLines = await prisma.movementLine.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const movementLineWithIdOnly = await prisma.movementLine.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MovementLineFindManyArgs>(args?: Prisma.SelectSubset<T, MovementLineFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MovementLinePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MovementLine.
   * @param {MovementLineCreateArgs} args - Arguments to create a MovementLine.
   * @example
   * // Create one MovementLine
   * const MovementLine = await prisma.movementLine.create({
   *   data: {
   *     // ... data to create a MovementLine
   *   }
   * })
   * 
   */
  create<T extends MovementLineCreateArgs>(args: Prisma.SelectSubset<T, MovementLineCreateArgs<ExtArgs>>): Prisma.Prisma__MovementLineClient<runtime.Types.Result.GetResult<Prisma.$MovementLinePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MovementLines.
   * @param {MovementLineCreateManyArgs} args - Arguments to create many MovementLines.
   * @example
   * // Create many MovementLines
   * const movementLine = await prisma.movementLine.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MovementLineCreateManyArgs>(args?: Prisma.SelectSubset<T, MovementLineCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MovementLines and returns the data saved in the database.
   * @param {MovementLineCreateManyAndReturnArgs} args - Arguments to create many MovementLines.
   * @example
   * // Create many MovementLines
   * const movementLine = await prisma.movementLine.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MovementLines and only return the `id`
   * const movementLineWithIdOnly = await prisma.movementLine.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MovementLineCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MovementLineCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MovementLinePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MovementLine.
   * @param {MovementLineDeleteArgs} args - Arguments to delete one MovementLine.
   * @example
   * // Delete one MovementLine
   * const MovementLine = await prisma.movementLine.delete({
   *   where: {
   *     // ... filter to delete one MovementLine
   *   }
   * })
   * 
   */
  delete<T extends MovementLineDeleteArgs>(args: Prisma.SelectSubset<T, MovementLineDeleteArgs<ExtArgs>>): Prisma.Prisma__MovementLineClient<runtime.Types.Result.GetResult<Prisma.$MovementLinePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MovementLine.
   * @param {MovementLineUpdateArgs} args - Arguments to update one MovementLine.
   * @example
   * // Update one MovementLine
   * const movementLine = await prisma.movementLine.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MovementLineUpdateArgs>(args: Prisma.SelectSubset<T, MovementLineUpdateArgs<ExtArgs>>): Prisma.Prisma__MovementLineClient<runtime.Types.Result.GetResult<Prisma.$MovementLinePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MovementLines.
   * @param {MovementLineDeleteManyArgs} args - Arguments to filter MovementLines to delete.
   * @example
   * // Delete a few MovementLines
   * const { count } = await prisma.movementLine.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MovementLineDeleteManyArgs>(args?: Prisma.SelectSubset<T, MovementLineDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MovementLines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementLineUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MovementLines
   * const movementLine = await prisma.movementLine.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MovementLineUpdateManyArgs>(args: Prisma.SelectSubset<T, MovementLineUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MovementLines and returns the data updated in the database.
   * @param {MovementLineUpdateManyAndReturnArgs} args - Arguments to update many MovementLines.
   * @example
   * // Update many MovementLines
   * const movementLine = await prisma.movementLine.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MovementLines and only return the `id`
   * const movementLineWithIdOnly = await prisma.movementLine.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MovementLineUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MovementLineUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MovementLinePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MovementLine.
   * @param {MovementLineUpsertArgs} args - Arguments to update or create a MovementLine.
   * @example
   * // Update or create a MovementLine
   * const movementLine = await prisma.movementLine.upsert({
   *   create: {
   *     // ... data to create a MovementLine
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MovementLine we want to update
   *   }
   * })
   */
  upsert<T extends MovementLineUpsertArgs>(args: Prisma.SelectSubset<T, MovementLineUpsertArgs<ExtArgs>>): Prisma.Prisma__MovementLineClient<runtime.Types.Result.GetResult<Prisma.$MovementLinePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MovementLines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementLineCountArgs} args - Arguments to filter MovementLines to count.
   * @example
   * // Count the number of MovementLines
   * const count = await prisma.movementLine.count({
   *   where: {
   *     // ... the filter for the MovementLines we want to count
   *   }
   * })
  **/
  count<T extends MovementLineCountArgs>(
    args?: Prisma.Subset<T, MovementLineCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MovementLineCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MovementLine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementLineAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MovementLineAggregateArgs>(args: Prisma.Subset<T, MovementLineAggregateArgs>): Prisma.PrismaPromise<GetMovementLineAggregateType<T>>

  /**
   * Group by MovementLine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementLineGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MovementLineGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MovementLineGroupByArgs['orderBy'] }
      : { orderBy?: MovementLineGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MovementLineGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMovementLineGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MovementLine model
 */
readonly fields: MovementLineFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MovementLine.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MovementLineClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  movement<T extends Prisma.MovementDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MovementDefaultArgs<ExtArgs>>): Prisma.Prisma__MovementClient<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MovementLine model
 */
export interface MovementLineFieldRefs {
  readonly id: Prisma.FieldRef<"MovementLine", 'Int'>
  readonly movementId: Prisma.FieldRef<"MovementLine", 'Int'>
  readonly productId: Prisma.FieldRef<"MovementLine", 'Int'>
  readonly quantity: Prisma.FieldRef<"MovementLine", 'Int'>
  readonly unitPrice: Prisma.FieldRef<"MovementLine", 'Decimal'>
  readonly subtotal: Prisma.FieldRef<"MovementLine", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"MovementLine", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MovementLine", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MovementLine findUnique
 */
export type MovementLineFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineInclude<ExtArgs> | null
  /**
   * Filter, which MovementLine to fetch.
   */
  where: Prisma.MovementLineWhereUniqueInput
}

/**
 * MovementLine findUniqueOrThrow
 */
export type MovementLineFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineInclude<ExtArgs> | null
  /**
   * Filter, which MovementLine to fetch.
   */
  where: Prisma.MovementLineWhereUniqueInput
}

/**
 * MovementLine findFirst
 */
export type MovementLineFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineInclude<ExtArgs> | null
  /**
   * Filter, which MovementLine to fetch.
   */
  where?: Prisma.MovementLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MovementLines to fetch.
   */
  orderBy?: Prisma.MovementLineOrderByWithRelationInput | Prisma.MovementLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MovementLines.
   */
  cursor?: Prisma.MovementLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MovementLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MovementLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MovementLines.
   */
  distinct?: Prisma.MovementLineScalarFieldEnum | Prisma.MovementLineScalarFieldEnum[]
}

/**
 * MovementLine findFirstOrThrow
 */
export type MovementLineFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineInclude<ExtArgs> | null
  /**
   * Filter, which MovementLine to fetch.
   */
  where?: Prisma.MovementLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MovementLines to fetch.
   */
  orderBy?: Prisma.MovementLineOrderByWithRelationInput | Prisma.MovementLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MovementLines.
   */
  cursor?: Prisma.MovementLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MovementLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MovementLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MovementLines.
   */
  distinct?: Prisma.MovementLineScalarFieldEnum | Prisma.MovementLineScalarFieldEnum[]
}

/**
 * MovementLine findMany
 */
export type MovementLineFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineInclude<ExtArgs> | null
  /**
   * Filter, which MovementLines to fetch.
   */
  where?: Prisma.MovementLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MovementLines to fetch.
   */
  orderBy?: Prisma.MovementLineOrderByWithRelationInput | Prisma.MovementLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MovementLines.
   */
  cursor?: Prisma.MovementLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MovementLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MovementLines.
   */
  skip?: number
  distinct?: Prisma.MovementLineScalarFieldEnum | Prisma.MovementLineScalarFieldEnum[]
}

/**
 * MovementLine create
 */
export type MovementLineCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineInclude<ExtArgs> | null
  /**
   * The data needed to create a MovementLine.
   */
  data: Prisma.XOR<Prisma.MovementLineCreateInput, Prisma.MovementLineUncheckedCreateInput>
}

/**
 * MovementLine createMany
 */
export type MovementLineCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MovementLines.
   */
  data: Prisma.MovementLineCreateManyInput | Prisma.MovementLineCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MovementLine createManyAndReturn
 */
export type MovementLineCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * The data used to create many MovementLines.
   */
  data: Prisma.MovementLineCreateManyInput | Prisma.MovementLineCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MovementLine update
 */
export type MovementLineUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineInclude<ExtArgs> | null
  /**
   * The data needed to update a MovementLine.
   */
  data: Prisma.XOR<Prisma.MovementLineUpdateInput, Prisma.MovementLineUncheckedUpdateInput>
  /**
   * Choose, which MovementLine to update.
   */
  where: Prisma.MovementLineWhereUniqueInput
}

/**
 * MovementLine updateMany
 */
export type MovementLineUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MovementLines.
   */
  data: Prisma.XOR<Prisma.MovementLineUpdateManyMutationInput, Prisma.MovementLineUncheckedUpdateManyInput>
  /**
   * Filter which MovementLines to update
   */
  where?: Prisma.MovementLineWhereInput
  /**
   * Limit how many MovementLines to update.
   */
  limit?: number
}

/**
 * MovementLine updateManyAndReturn
 */
export type MovementLineUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * The data used to update MovementLines.
   */
  data: Prisma.XOR<Prisma.MovementLineUpdateManyMutationInput, Prisma.MovementLineUncheckedUpdateManyInput>
  /**
   * Filter which MovementLines to update
   */
  where?: Prisma.MovementLineWhereInput
  /**
   * Limit how many MovementLines to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MovementLine upsert
 */
export type MovementLineUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineInclude<ExtArgs> | null
  /**
   * The filter to search for the MovementLine to update in case it exists.
   */
  where: Prisma.MovementLineWhereUniqueInput
  /**
   * In case the MovementLine found by the `where` argument doesn't exist, create a new MovementLine with this data.
   */
  create: Prisma.XOR<Prisma.MovementLineCreateInput, Prisma.MovementLineUncheckedCreateInput>
  /**
   * In case the MovementLine was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MovementLineUpdateInput, Prisma.MovementLineUncheckedUpdateInput>
}

/**
 * MovementLine delete
 */
export type MovementLineDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineInclude<ExtArgs> | null
  /**
   * Filter which MovementLine to delete.
   */
  where: Prisma.MovementLineWhereUniqueInput
}

/**
 * MovementLine deleteMany
 */
export type MovementLineDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MovementLines to delete
   */
  where?: Prisma.MovementLineWhereInput
  /**
   * Limit how many MovementLines to delete.
   */
  limit?: number
}

/**
 * MovementLine without action
 */
export type MovementLineDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineInclude<ExtArgs> | null
}
