
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Movement` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Movement
 * 
 */
export type MovementModel = runtime.Types.Result.DefaultSelection<Prisma.$MovementPayload>

export type AggregateMovement = {
  _count: MovementCountAggregateOutputType | null
  _avg: MovementAvgAggregateOutputType | null
  _sum: MovementSumAggregateOutputType | null
  _min: MovementMinAggregateOutputType | null
  _max: MovementMaxAggregateOutputType | null
}

export type MovementAvgAggregateOutputType = {
  id: number | null
  operationId: number | null
  createdById: number | null
  updatedById: number | null
}

export type MovementSumAggregateOutputType = {
  id: number | null
  operationId: number | null
  createdById: number | null
  updatedById: number | null
}

export type MovementMinAggregateOutputType = {
  id: number | null
  movementDate: Date | null
  operationId: number | null
  createdById: number | null
  updatedById: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MovementMaxAggregateOutputType = {
  id: number | null
  movementDate: Date | null
  operationId: number | null
  createdById: number | null
  updatedById: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MovementCountAggregateOutputType = {
  id: number
  movementDate: number
  operationId: number
  createdById: number
  updatedById: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MovementAvgAggregateInputType = {
  id?: true
  operationId?: true
  createdById?: true
  updatedById?: true
}

export type MovementSumAggregateInputType = {
  id?: true
  operationId?: true
  createdById?: true
  updatedById?: true
}

export type MovementMinAggregateInputType = {
  id?: true
  movementDate?: true
  operationId?: true
  createdById?: true
  updatedById?: true
  createdAt?: true
  updatedAt?: true
}

export type MovementMaxAggregateInputType = {
  id?: true
  movementDate?: true
  operationId?: true
  createdById?: true
  updatedById?: true
  createdAt?: true
  updatedAt?: true
}

export type MovementCountAggregateInputType = {
  id?: true
  movementDate?: true
  operationId?: true
  createdById?: true
  updatedById?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MovementAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Movement to aggregate.
   */
  where?: Prisma.MovementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Movements to fetch.
   */
  orderBy?: Prisma.MovementOrderByWithRelationInput | Prisma.MovementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MovementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Movements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Movements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Movements
  **/
  _count?: true | MovementCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MovementAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MovementSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MovementMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MovementMaxAggregateInputType
}

export type GetMovementAggregateType<T extends MovementAggregateArgs> = {
      [P in keyof T & keyof AggregateMovement]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMovement[P]>
    : Prisma.GetScalarType<T[P], AggregateMovement[P]>
}




export type MovementGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MovementWhereInput
  orderBy?: Prisma.MovementOrderByWithAggregationInput | Prisma.MovementOrderByWithAggregationInput[]
  by: Prisma.MovementScalarFieldEnum[] | Prisma.MovementScalarFieldEnum
  having?: Prisma.MovementScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MovementCountAggregateInputType | true
  _avg?: MovementAvgAggregateInputType
  _sum?: MovementSumAggregateInputType
  _min?: MovementMinAggregateInputType
  _max?: MovementMaxAggregateInputType
}

export type MovementGroupByOutputType = {
  id: number
  movementDate: Date
  operationId: number
  createdById: number
  updatedById: number
  createdAt: Date
  updatedAt: Date
  _count: MovementCountAggregateOutputType | null
  _avg: MovementAvgAggregateOutputType | null
  _sum: MovementSumAggregateOutputType | null
  _min: MovementMinAggregateOutputType | null
  _max: MovementMaxAggregateOutputType | null
}

type GetMovementGroupByPayload<T extends MovementGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MovementGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MovementGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MovementGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MovementGroupByOutputType[P]>
      }
    >
  >



export type MovementWhereInput = {
  AND?: Prisma.MovementWhereInput | Prisma.MovementWhereInput[]
  OR?: Prisma.MovementWhereInput[]
  NOT?: Prisma.MovementWhereInput | Prisma.MovementWhereInput[]
  id?: Prisma.IntFilter<"Movement"> | number
  movementDate?: Prisma.DateTimeFilter<"Movement"> | Date | string
  operationId?: Prisma.IntFilter<"Movement"> | number
  createdById?: Prisma.IntFilter<"Movement"> | number
  updatedById?: Prisma.IntFilter<"Movement"> | number
  createdAt?: Prisma.DateTimeFilter<"Movement"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Movement"> | Date | string
  lines?: Prisma.MovementLineListRelationFilter
  operation?: Prisma.XOR<Prisma.OperationScalarRelationFilter, Prisma.OperationWhereInput>
  createdBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  updatedBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type MovementOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  movementDate?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lines?: Prisma.MovementLineOrderByRelationAggregateInput
  operation?: Prisma.OperationOrderByWithRelationInput
  createdBy?: Prisma.UserOrderByWithRelationInput
  updatedBy?: Prisma.UserOrderByWithRelationInput
}

export type MovementWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MovementWhereInput | Prisma.MovementWhereInput[]
  OR?: Prisma.MovementWhereInput[]
  NOT?: Prisma.MovementWhereInput | Prisma.MovementWhereInput[]
  movementDate?: Prisma.DateTimeFilter<"Movement"> | Date | string
  operationId?: Prisma.IntFilter<"Movement"> | number
  createdById?: Prisma.IntFilter<"Movement"> | number
  updatedById?: Prisma.IntFilter<"Movement"> | number
  createdAt?: Prisma.DateTimeFilter<"Movement"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Movement"> | Date | string
  lines?: Prisma.MovementLineListRelationFilter
  operation?: Prisma.XOR<Prisma.OperationScalarRelationFilter, Prisma.OperationWhereInput>
  createdBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  updatedBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type MovementOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  movementDate?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MovementCountOrderByAggregateInput
  _avg?: Prisma.MovementAvgOrderByAggregateInput
  _max?: Prisma.MovementMaxOrderByAggregateInput
  _min?: Prisma.MovementMinOrderByAggregateInput
  _sum?: Prisma.MovementSumOrderByAggregateInput
}

export type MovementScalarWhereWithAggregatesInput = {
  AND?: Prisma.MovementScalarWhereWithAggregatesInput | Prisma.MovementScalarWhereWithAggregatesInput[]
  OR?: Prisma.MovementScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MovementScalarWhereWithAggregatesInput | Prisma.MovementScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Movement"> | number
  movementDate?: Prisma.DateTimeWithAggregatesFilter<"Movement"> | Date | string
  operationId?: Prisma.IntWithAggregatesFilter<"Movement"> | number
  createdById?: Prisma.IntWithAggregatesFilter<"Movement"> | number
  updatedById?: Prisma.IntWithAggregatesFilter<"Movement"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Movement"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Movement"> | Date | string
}

export type MovementCreateInput = {
  movementDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  lines?: Prisma.MovementLineCreateNestedManyWithoutMovementInput
  operation: Prisma.OperationCreateNestedOneWithoutMovementsInput
  createdBy: Prisma.UserCreateNestedOneWithoutCreatedMovementsInput
  updatedBy: Prisma.UserCreateNestedOneWithoutUpdatedMovementsInput
}

export type MovementUncheckedCreateInput = {
  id?: number
  movementDate?: Date | string
  operationId: number
  createdById: number
  updatedById: number
  createdAt?: Date | string
  updatedAt?: Date | string
  lines?: Prisma.MovementLineUncheckedCreateNestedManyWithoutMovementInput
}

export type MovementUpdateInput = {
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lines?: Prisma.MovementLineUpdateManyWithoutMovementNestedInput
  operation?: Prisma.OperationUpdateOneRequiredWithoutMovementsNestedInput
  createdBy?: Prisma.UserUpdateOneRequiredWithoutCreatedMovementsNestedInput
  updatedBy?: Prisma.UserUpdateOneRequiredWithoutUpdatedMovementsNestedInput
}

export type MovementUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operationId?: Prisma.IntFieldUpdateOperationsInput | number
  createdById?: Prisma.IntFieldUpdateOperationsInput | number
  updatedById?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lines?: Prisma.MovementLineUncheckedUpdateManyWithoutMovementNestedInput
}

export type MovementCreateManyInput = {
  id?: number
  movementDate?: Date | string
  operationId: number
  createdById: number
  updatedById: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MovementUpdateManyMutationInput = {
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MovementUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operationId?: Prisma.IntFieldUpdateOperationsInput | number
  createdById?: Prisma.IntFieldUpdateOperationsInput | number
  updatedById?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MovementListRelationFilter = {
  every?: Prisma.MovementWhereInput
  some?: Prisma.MovementWhereInput
  none?: Prisma.MovementWhereInput
}

export type MovementOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MovementCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  movementDate?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MovementAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
}

export type MovementMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  movementDate?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MovementMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  movementDate?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MovementSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  operationId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
}

export type MovementScalarRelationFilter = {
  is?: Prisma.MovementWhereInput
  isNot?: Prisma.MovementWhereInput
}

export type MovementCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutCreatedByInput, Prisma.MovementUncheckedCreateWithoutCreatedByInput> | Prisma.MovementCreateWithoutCreatedByInput[] | Prisma.MovementUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutCreatedByInput | Prisma.MovementCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.MovementCreateManyCreatedByInputEnvelope
  connect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
}

export type MovementCreateNestedManyWithoutUpdatedByInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutUpdatedByInput, Prisma.MovementUncheckedCreateWithoutUpdatedByInput> | Prisma.MovementCreateWithoutUpdatedByInput[] | Prisma.MovementUncheckedCreateWithoutUpdatedByInput[]
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutUpdatedByInput | Prisma.MovementCreateOrConnectWithoutUpdatedByInput[]
  createMany?: Prisma.MovementCreateManyUpdatedByInputEnvelope
  connect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
}

export type MovementUncheckedCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutCreatedByInput, Prisma.MovementUncheckedCreateWithoutCreatedByInput> | Prisma.MovementCreateWithoutCreatedByInput[] | Prisma.MovementUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutCreatedByInput | Prisma.MovementCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.MovementCreateManyCreatedByInputEnvelope
  connect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
}

export type MovementUncheckedCreateNestedManyWithoutUpdatedByInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutUpdatedByInput, Prisma.MovementUncheckedCreateWithoutUpdatedByInput> | Prisma.MovementCreateWithoutUpdatedByInput[] | Prisma.MovementUncheckedCreateWithoutUpdatedByInput[]
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutUpdatedByInput | Prisma.MovementCreateOrConnectWithoutUpdatedByInput[]
  createMany?: Prisma.MovementCreateManyUpdatedByInputEnvelope
  connect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
}

export type MovementUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutCreatedByInput, Prisma.MovementUncheckedCreateWithoutCreatedByInput> | Prisma.MovementCreateWithoutCreatedByInput[] | Prisma.MovementUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutCreatedByInput | Prisma.MovementCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.MovementUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.MovementUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.MovementCreateManyCreatedByInputEnvelope
  set?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  disconnect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  delete?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  connect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  update?: Prisma.MovementUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.MovementUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.MovementUpdateManyWithWhereWithoutCreatedByInput | Prisma.MovementUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.MovementScalarWhereInput | Prisma.MovementScalarWhereInput[]
}

export type MovementUpdateManyWithoutUpdatedByNestedInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutUpdatedByInput, Prisma.MovementUncheckedCreateWithoutUpdatedByInput> | Prisma.MovementCreateWithoutUpdatedByInput[] | Prisma.MovementUncheckedCreateWithoutUpdatedByInput[]
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutUpdatedByInput | Prisma.MovementCreateOrConnectWithoutUpdatedByInput[]
  upsert?: Prisma.MovementUpsertWithWhereUniqueWithoutUpdatedByInput | Prisma.MovementUpsertWithWhereUniqueWithoutUpdatedByInput[]
  createMany?: Prisma.MovementCreateManyUpdatedByInputEnvelope
  set?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  disconnect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  delete?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  connect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  update?: Prisma.MovementUpdateWithWhereUniqueWithoutUpdatedByInput | Prisma.MovementUpdateWithWhereUniqueWithoutUpdatedByInput[]
  updateMany?: Prisma.MovementUpdateManyWithWhereWithoutUpdatedByInput | Prisma.MovementUpdateManyWithWhereWithoutUpdatedByInput[]
  deleteMany?: Prisma.MovementScalarWhereInput | Prisma.MovementScalarWhereInput[]
}

export type MovementUncheckedUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutCreatedByInput, Prisma.MovementUncheckedCreateWithoutCreatedByInput> | Prisma.MovementCreateWithoutCreatedByInput[] | Prisma.MovementUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutCreatedByInput | Prisma.MovementCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.MovementUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.MovementUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.MovementCreateManyCreatedByInputEnvelope
  set?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  disconnect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  delete?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  connect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  update?: Prisma.MovementUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.MovementUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.MovementUpdateManyWithWhereWithoutCreatedByInput | Prisma.MovementUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.MovementScalarWhereInput | Prisma.MovementScalarWhereInput[]
}

export type MovementUncheckedUpdateManyWithoutUpdatedByNestedInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutUpdatedByInput, Prisma.MovementUncheckedCreateWithoutUpdatedByInput> | Prisma.MovementCreateWithoutUpdatedByInput[] | Prisma.MovementUncheckedCreateWithoutUpdatedByInput[]
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutUpdatedByInput | Prisma.MovementCreateOrConnectWithoutUpdatedByInput[]
  upsert?: Prisma.MovementUpsertWithWhereUniqueWithoutUpdatedByInput | Prisma.MovementUpsertWithWhereUniqueWithoutUpdatedByInput[]
  createMany?: Prisma.MovementCreateManyUpdatedByInputEnvelope
  set?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  disconnect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  delete?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  connect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  update?: Prisma.MovementUpdateWithWhereUniqueWithoutUpdatedByInput | Prisma.MovementUpdateWithWhereUniqueWithoutUpdatedByInput[]
  updateMany?: Prisma.MovementUpdateManyWithWhereWithoutUpdatedByInput | Prisma.MovementUpdateManyWithWhereWithoutUpdatedByInput[]
  deleteMany?: Prisma.MovementScalarWhereInput | Prisma.MovementScalarWhereInput[]
}

export type MovementCreateNestedOneWithoutLinesInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutLinesInput, Prisma.MovementUncheckedCreateWithoutLinesInput>
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutLinesInput
  connect?: Prisma.MovementWhereUniqueInput
}

export type MovementUpdateOneRequiredWithoutLinesNestedInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutLinesInput, Prisma.MovementUncheckedCreateWithoutLinesInput>
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutLinesInput
  upsert?: Prisma.MovementUpsertWithoutLinesInput
  connect?: Prisma.MovementWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MovementUpdateToOneWithWhereWithoutLinesInput, Prisma.MovementUpdateWithoutLinesInput>, Prisma.MovementUncheckedUpdateWithoutLinesInput>
}

export type MovementCreateNestedManyWithoutOperationInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutOperationInput, Prisma.MovementUncheckedCreateWithoutOperationInput> | Prisma.MovementCreateWithoutOperationInput[] | Prisma.MovementUncheckedCreateWithoutOperationInput[]
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutOperationInput | Prisma.MovementCreateOrConnectWithoutOperationInput[]
  createMany?: Prisma.MovementCreateManyOperationInputEnvelope
  connect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
}

export type MovementUncheckedCreateNestedManyWithoutOperationInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutOperationInput, Prisma.MovementUncheckedCreateWithoutOperationInput> | Prisma.MovementCreateWithoutOperationInput[] | Prisma.MovementUncheckedCreateWithoutOperationInput[]
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutOperationInput | Prisma.MovementCreateOrConnectWithoutOperationInput[]
  createMany?: Prisma.MovementCreateManyOperationInputEnvelope
  connect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
}

export type MovementUpdateManyWithoutOperationNestedInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutOperationInput, Prisma.MovementUncheckedCreateWithoutOperationInput> | Prisma.MovementCreateWithoutOperationInput[] | Prisma.MovementUncheckedCreateWithoutOperationInput[]
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutOperationInput | Prisma.MovementCreateOrConnectWithoutOperationInput[]
  upsert?: Prisma.MovementUpsertWithWhereUniqueWithoutOperationInput | Prisma.MovementUpsertWithWhereUniqueWithoutOperationInput[]
  createMany?: Prisma.MovementCreateManyOperationInputEnvelope
  set?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  disconnect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  delete?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  connect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  update?: Prisma.MovementUpdateWithWhereUniqueWithoutOperationInput | Prisma.MovementUpdateWithWhereUniqueWithoutOperationInput[]
  updateMany?: Prisma.MovementUpdateManyWithWhereWithoutOperationInput | Prisma.MovementUpdateManyWithWhereWithoutOperationInput[]
  deleteMany?: Prisma.MovementScalarWhereInput | Prisma.MovementScalarWhereInput[]
}

export type MovementUncheckedUpdateManyWithoutOperationNestedInput = {
  create?: Prisma.XOR<Prisma.MovementCreateWithoutOperationInput, Prisma.MovementUncheckedCreateWithoutOperationInput> | Prisma.MovementCreateWithoutOperationInput[] | Prisma.MovementUncheckedCreateWithoutOperationInput[]
  connectOrCreate?: Prisma.MovementCreateOrConnectWithoutOperationInput | Prisma.MovementCreateOrConnectWithoutOperationInput[]
  upsert?: Prisma.MovementUpsertWithWhereUniqueWithoutOperationInput | Prisma.MovementUpsertWithWhereUniqueWithoutOperationInput[]
  createMany?: Prisma.MovementCreateManyOperationInputEnvelope
  set?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  disconnect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  delete?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  connect?: Prisma.MovementWhereUniqueInput | Prisma.MovementWhereUniqueInput[]
  update?: Prisma.MovementUpdateWithWhereUniqueWithoutOperationInput | Prisma.MovementUpdateWithWhereUniqueWithoutOperationInput[]
  updateMany?: Prisma.MovementUpdateManyWithWhereWithoutOperationInput | Prisma.MovementUpdateManyWithWhereWithoutOperationInput[]
  deleteMany?: Prisma.MovementScalarWhereInput | Prisma.MovementScalarWhereInput[]
}

export type MovementCreateWithoutCreatedByInput = {
  movementDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  lines?: Prisma.MovementLineCreateNestedManyWithoutMovementInput
  operation: Prisma.OperationCreateNestedOneWithoutMovementsInput
  updatedBy: Prisma.UserCreateNestedOneWithoutUpdatedMovementsInput
}

export type MovementUncheckedCreateWithoutCreatedByInput = {
  id?: number
  movementDate?: Date | string
  operationId: number
  updatedById: number
  createdAt?: Date | string
  updatedAt?: Date | string
  lines?: Prisma.MovementLineUncheckedCreateNestedManyWithoutMovementInput
}

export type MovementCreateOrConnectWithoutCreatedByInput = {
  where: Prisma.MovementWhereUniqueInput
  create: Prisma.XOR<Prisma.MovementCreateWithoutCreatedByInput, Prisma.MovementUncheckedCreateWithoutCreatedByInput>
}

export type MovementCreateManyCreatedByInputEnvelope = {
  data: Prisma.MovementCreateManyCreatedByInput | Prisma.MovementCreateManyCreatedByInput[]
  skipDuplicates?: boolean
}

export type MovementCreateWithoutUpdatedByInput = {
  movementDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  lines?: Prisma.MovementLineCreateNestedManyWithoutMovementInput
  operation: Prisma.OperationCreateNestedOneWithoutMovementsInput
  createdBy: Prisma.UserCreateNestedOneWithoutCreatedMovementsInput
}

export type MovementUncheckedCreateWithoutUpdatedByInput = {
  id?: number
  movementDate?: Date | string
  operationId: number
  createdById: number
  createdAt?: Date | string
  updatedAt?: Date | string
  lines?: Prisma.MovementLineUncheckedCreateNestedManyWithoutMovementInput
}

export type MovementCreateOrConnectWithoutUpdatedByInput = {
  where: Prisma.MovementWhereUniqueInput
  create: Prisma.XOR<Prisma.MovementCreateWithoutUpdatedByInput, Prisma.MovementUncheckedCreateWithoutUpdatedByInput>
}

export type MovementCreateManyUpdatedByInputEnvelope = {
  data: Prisma.MovementCreateManyUpdatedByInput | Prisma.MovementCreateManyUpdatedByInput[]
  skipDuplicates?: boolean
}

export type MovementUpsertWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.MovementWhereUniqueInput
  update: Prisma.XOR<Prisma.MovementUpdateWithoutCreatedByInput, Prisma.MovementUncheckedUpdateWithoutCreatedByInput>
  create: Prisma.XOR<Prisma.MovementCreateWithoutCreatedByInput, Prisma.MovementUncheckedCreateWithoutCreatedByInput>
}

export type MovementUpdateWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.MovementWhereUniqueInput
  data: Prisma.XOR<Prisma.MovementUpdateWithoutCreatedByInput, Prisma.MovementUncheckedUpdateWithoutCreatedByInput>
}

export type MovementUpdateManyWithWhereWithoutCreatedByInput = {
  where: Prisma.MovementScalarWhereInput
  data: Prisma.XOR<Prisma.MovementUpdateManyMutationInput, Prisma.MovementUncheckedUpdateManyWithoutCreatedByInput>
}

export type MovementScalarWhereInput = {
  AND?: Prisma.MovementScalarWhereInput | Prisma.MovementScalarWhereInput[]
  OR?: Prisma.MovementScalarWhereInput[]
  NOT?: Prisma.MovementScalarWhereInput | Prisma.MovementScalarWhereInput[]
  id?: Prisma.IntFilter<"Movement"> | number
  movementDate?: Prisma.DateTimeFilter<"Movement"> | Date | string
  operationId?: Prisma.IntFilter<"Movement"> | number
  createdById?: Prisma.IntFilter<"Movement"> | number
  updatedById?: Prisma.IntFilter<"Movement"> | number
  createdAt?: Prisma.DateTimeFilter<"Movement"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Movement"> | Date | string
}

export type MovementUpsertWithWhereUniqueWithoutUpdatedByInput = {
  where: Prisma.MovementWhereUniqueInput
  update: Prisma.XOR<Prisma.MovementUpdateWithoutUpdatedByInput, Prisma.MovementUncheckedUpdateWithoutUpdatedByInput>
  create: Prisma.XOR<Prisma.MovementCreateWithoutUpdatedByInput, Prisma.MovementUncheckedCreateWithoutUpdatedByInput>
}

export type MovementUpdateWithWhereUniqueWithoutUpdatedByInput = {
  where: Prisma.MovementWhereUniqueInput
  data: Prisma.XOR<Prisma.MovementUpdateWithoutUpdatedByInput, Prisma.MovementUncheckedUpdateWithoutUpdatedByInput>
}

export type MovementUpdateManyWithWhereWithoutUpdatedByInput = {
  where: Prisma.MovementScalarWhereInput
  data: Prisma.XOR<Prisma.MovementUpdateManyMutationInput, Prisma.MovementUncheckedUpdateManyWithoutUpdatedByInput>
}

export type MovementCreateWithoutLinesInput = {
  movementDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  operation: Prisma.OperationCreateNestedOneWithoutMovementsInput
  createdBy: Prisma.UserCreateNestedOneWithoutCreatedMovementsInput
  updatedBy: Prisma.UserCreateNestedOneWithoutUpdatedMovementsInput
}

export type MovementUncheckedCreateWithoutLinesInput = {
  id?: number
  movementDate?: Date | string
  operationId: number
  createdById: number
  updatedById: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MovementCreateOrConnectWithoutLinesInput = {
  where: Prisma.MovementWhereUniqueInput
  create: Prisma.XOR<Prisma.MovementCreateWithoutLinesInput, Prisma.MovementUncheckedCreateWithoutLinesInput>
}

export type MovementUpsertWithoutLinesInput = {
  update: Prisma.XOR<Prisma.MovementUpdateWithoutLinesInput, Prisma.MovementUncheckedUpdateWithoutLinesInput>
  create: Prisma.XOR<Prisma.MovementCreateWithoutLinesInput, Prisma.MovementUncheckedCreateWithoutLinesInput>
  where?: Prisma.MovementWhereInput
}

export type MovementUpdateToOneWithWhereWithoutLinesInput = {
  where?: Prisma.MovementWhereInput
  data: Prisma.XOR<Prisma.MovementUpdateWithoutLinesInput, Prisma.MovementUncheckedUpdateWithoutLinesInput>
}

export type MovementUpdateWithoutLinesInput = {
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operation?: Prisma.OperationUpdateOneRequiredWithoutMovementsNestedInput
  createdBy?: Prisma.UserUpdateOneRequiredWithoutCreatedMovementsNestedInput
  updatedBy?: Prisma.UserUpdateOneRequiredWithoutUpdatedMovementsNestedInput
}

export type MovementUncheckedUpdateWithoutLinesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operationId?: Prisma.IntFieldUpdateOperationsInput | number
  createdById?: Prisma.IntFieldUpdateOperationsInput | number
  updatedById?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MovementCreateWithoutOperationInput = {
  movementDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  lines?: Prisma.MovementLineCreateNestedManyWithoutMovementInput
  createdBy: Prisma.UserCreateNestedOneWithoutCreatedMovementsInput
  updatedBy: Prisma.UserCreateNestedOneWithoutUpdatedMovementsInput
}

export type MovementUncheckedCreateWithoutOperationInput = {
  id?: number
  movementDate?: Date | string
  createdById: number
  updatedById: number
  createdAt?: Date | string
  updatedAt?: Date | string
  lines?: Prisma.MovementLineUncheckedCreateNestedManyWithoutMovementInput
}

export type MovementCreateOrConnectWithoutOperationInput = {
  where: Prisma.MovementWhereUniqueInput
  create: Prisma.XOR<Prisma.MovementCreateWithoutOperationInput, Prisma.MovementUncheckedCreateWithoutOperationInput>
}

export type MovementCreateManyOperationInputEnvelope = {
  data: Prisma.MovementCreateManyOperationInput | Prisma.MovementCreateManyOperationInput[]
  skipDuplicates?: boolean
}

export type MovementUpsertWithWhereUniqueWithoutOperationInput = {
  where: Prisma.MovementWhereUniqueInput
  update: Prisma.XOR<Prisma.MovementUpdateWithoutOperationInput, Prisma.MovementUncheckedUpdateWithoutOperationInput>
  create: Prisma.XOR<Prisma.MovementCreateWithoutOperationInput, Prisma.MovementUncheckedCreateWithoutOperationInput>
}

export type MovementUpdateWithWhereUniqueWithoutOperationInput = {
  where: Prisma.MovementWhereUniqueInput
  data: Prisma.XOR<Prisma.MovementUpdateWithoutOperationInput, Prisma.MovementUncheckedUpdateWithoutOperationInput>
}

export type MovementUpdateManyWithWhereWithoutOperationInput = {
  where: Prisma.MovementScalarWhereInput
  data: Prisma.XOR<Prisma.MovementUpdateManyMutationInput, Prisma.MovementUncheckedUpdateManyWithoutOperationInput>
}

export type MovementCreateManyCreatedByInput = {
  id?: number
  movementDate?: Date | string
  operationId: number
  updatedById: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MovementCreateManyUpdatedByInput = {
  id?: number
  movementDate?: Date | string
  operationId: number
  createdById: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MovementUpdateWithoutCreatedByInput = {
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lines?: Prisma.MovementLineUpdateManyWithoutMovementNestedInput
  operation?: Prisma.OperationUpdateOneRequiredWithoutMovementsNestedInput
  updatedBy?: Prisma.UserUpdateOneRequiredWithoutUpdatedMovementsNestedInput
}

export type MovementUncheckedUpdateWithoutCreatedByInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operationId?: Prisma.IntFieldUpdateOperationsInput | number
  updatedById?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lines?: Prisma.MovementLineUncheckedUpdateManyWithoutMovementNestedInput
}

export type MovementUncheckedUpdateManyWithoutCreatedByInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operationId?: Prisma.IntFieldUpdateOperationsInput | number
  updatedById?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MovementUpdateWithoutUpdatedByInput = {
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lines?: Prisma.MovementLineUpdateManyWithoutMovementNestedInput
  operation?: Prisma.OperationUpdateOneRequiredWithoutMovementsNestedInput
  createdBy?: Prisma.UserUpdateOneRequiredWithoutCreatedMovementsNestedInput
}

export type MovementUncheckedUpdateWithoutUpdatedByInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operationId?: Prisma.IntFieldUpdateOperationsInput | number
  createdById?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lines?: Prisma.MovementLineUncheckedUpdateManyWithoutMovementNestedInput
}

export type MovementUncheckedUpdateManyWithoutUpdatedByInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operationId?: Prisma.IntFieldUpdateOperationsInput | number
  createdById?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MovementCreateManyOperationInput = {
  id?: number
  movementDate?: Date | string
  createdById: number
  updatedById: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MovementUpdateWithoutOperationInput = {
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lines?: Prisma.MovementLineUpdateManyWithoutMovementNestedInput
  createdBy?: Prisma.UserUpdateOneRequiredWithoutCreatedMovementsNestedInput
  updatedBy?: Prisma.UserUpdateOneRequiredWithoutUpdatedMovementsNestedInput
}

export type MovementUncheckedUpdateWithoutOperationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.IntFieldUpdateOperationsInput | number
  updatedById?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lines?: Prisma.MovementLineUncheckedUpdateManyWithoutMovementNestedInput
}

export type MovementUncheckedUpdateManyWithoutOperationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  movementDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.IntFieldUpdateOperationsInput | number
  updatedById?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type MovementCountOutputType
 */

export type MovementCountOutputType = {
  lines: number
}

export type MovementCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lines?: boolean | MovementCountOutputTypeCountLinesArgs
}

/**
 * MovementCountOutputType without action
 */
export type MovementCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementCountOutputType
   */
  select?: Prisma.MovementCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MovementCountOutputType without action
 */
export type MovementCountOutputTypeCountLinesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MovementLineWhereInput
}


export type MovementSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  movementDate?: boolean
  operationId?: boolean
  createdById?: boolean
  updatedById?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lines?: boolean | Prisma.Movement$linesArgs<ExtArgs>
  operation?: boolean | Prisma.OperationDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  updatedBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.MovementCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["movement"]>

export type MovementSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  movementDate?: boolean
  operationId?: boolean
  createdById?: boolean
  updatedById?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  operation?: boolean | Prisma.OperationDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  updatedBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["movement"]>

export type MovementSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  movementDate?: boolean
  operationId?: boolean
  createdById?: boolean
  updatedById?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  operation?: boolean | Prisma.OperationDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  updatedBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["movement"]>

export type MovementSelectScalar = {
  id?: boolean
  movementDate?: boolean
  operationId?: boolean
  createdById?: boolean
  updatedById?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MovementOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "movementDate" | "operationId" | "createdById" | "updatedById" | "createdAt" | "updatedAt", ExtArgs["result"]["movement"]>
export type MovementInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lines?: boolean | Prisma.Movement$linesArgs<ExtArgs>
  operation?: boolean | Prisma.OperationDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  updatedBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.MovementCountOutputTypeDefaultArgs<ExtArgs>
}
export type MovementIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operation?: boolean | Prisma.OperationDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  updatedBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type MovementIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operation?: boolean | Prisma.OperationDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  updatedBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $MovementPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Movement"
  objects: {
    lines: Prisma.$MovementLinePayload<ExtArgs>[]
    operation: Prisma.$OperationPayload<ExtArgs>
    createdBy: Prisma.$UserPayload<ExtArgs>
    updatedBy: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    movementDate: Date
    operationId: number
    createdById: number
    updatedById: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["movement"]>
  composites: {}
}

export type MovementGetPayload<S extends boolean | null | undefined | MovementDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MovementPayload, S>

export type MovementCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MovementFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MovementCountAggregateInputType | true
  }

export interface MovementDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Movement'], meta: { name: 'Movement' } }
  /**
   * Find zero or one Movement that matches the filter.
   * @param {MovementFindUniqueArgs} args - Arguments to find a Movement
   * @example
   * // Get one Movement
   * const movement = await prisma.movement.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MovementFindUniqueArgs>(args: Prisma.SelectSubset<T, MovementFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MovementClient<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Movement that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MovementFindUniqueOrThrowArgs} args - Arguments to find a Movement
   * @example
   * // Get one Movement
   * const movement = await prisma.movement.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MovementFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MovementFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MovementClient<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Movement that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementFindFirstArgs} args - Arguments to find a Movement
   * @example
   * // Get one Movement
   * const movement = await prisma.movement.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MovementFindFirstArgs>(args?: Prisma.SelectSubset<T, MovementFindFirstArgs<ExtArgs>>): Prisma.Prisma__MovementClient<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Movement that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementFindFirstOrThrowArgs} args - Arguments to find a Movement
   * @example
   * // Get one Movement
   * const movement = await prisma.movement.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MovementFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MovementFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MovementClient<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Movements that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Movements
   * const movements = await prisma.movement.findMany()
   * 
   * // Get first 10 Movements
   * const movements = await prisma.movement.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const movementWithIdOnly = await prisma.movement.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MovementFindManyArgs>(args?: Prisma.SelectSubset<T, MovementFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Movement.
   * @param {MovementCreateArgs} args - Arguments to create a Movement.
   * @example
   * // Create one Movement
   * const Movement = await prisma.movement.create({
   *   data: {
   *     // ... data to create a Movement
   *   }
   * })
   * 
   */
  create<T extends MovementCreateArgs>(args: Prisma.SelectSubset<T, MovementCreateArgs<ExtArgs>>): Prisma.Prisma__MovementClient<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Movements.
   * @param {MovementCreateManyArgs} args - Arguments to create many Movements.
   * @example
   * // Create many Movements
   * const movement = await prisma.movement.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MovementCreateManyArgs>(args?: Prisma.SelectSubset<T, MovementCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Movements and returns the data saved in the database.
   * @param {MovementCreateManyAndReturnArgs} args - Arguments to create many Movements.
   * @example
   * // Create many Movements
   * const movement = await prisma.movement.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Movements and only return the `id`
   * const movementWithIdOnly = await prisma.movement.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MovementCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MovementCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Movement.
   * @param {MovementDeleteArgs} args - Arguments to delete one Movement.
   * @example
   * // Delete one Movement
   * const Movement = await prisma.movement.delete({
   *   where: {
   *     // ... filter to delete one Movement
   *   }
   * })
   * 
   */
  delete<T extends MovementDeleteArgs>(args: Prisma.SelectSubset<T, MovementDeleteArgs<ExtArgs>>): Prisma.Prisma__MovementClient<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Movement.
   * @param {MovementUpdateArgs} args - Arguments to update one Movement.
   * @example
   * // Update one Movement
   * const movement = await prisma.movement.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MovementUpdateArgs>(args: Prisma.SelectSubset<T, MovementUpdateArgs<ExtArgs>>): Prisma.Prisma__MovementClient<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Movements.
   * @param {MovementDeleteManyArgs} args - Arguments to filter Movements to delete.
   * @example
   * // Delete a few Movements
   * const { count } = await prisma.movement.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MovementDeleteManyArgs>(args?: Prisma.SelectSubset<T, MovementDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Movements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Movements
   * const movement = await prisma.movement.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MovementUpdateManyArgs>(args: Prisma.SelectSubset<T, MovementUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Movements and returns the data updated in the database.
   * @param {MovementUpdateManyAndReturnArgs} args - Arguments to update many Movements.
   * @example
   * // Update many Movements
   * const movement = await prisma.movement.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Movements and only return the `id`
   * const movementWithIdOnly = await prisma.movement.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MovementUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MovementUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Movement.
   * @param {MovementUpsertArgs} args - Arguments to update or create a Movement.
   * @example
   * // Update or create a Movement
   * const movement = await prisma.movement.upsert({
   *   create: {
   *     // ... data to create a Movement
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Movement we want to update
   *   }
   * })
   */
  upsert<T extends MovementUpsertArgs>(args: Prisma.SelectSubset<T, MovementUpsertArgs<ExtArgs>>): Prisma.Prisma__MovementClient<runtime.Types.Result.GetResult<Prisma.$MovementPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Movements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementCountArgs} args - Arguments to filter Movements to count.
   * @example
   * // Count the number of Movements
   * const count = await prisma.movement.count({
   *   where: {
   *     // ... the filter for the Movements we want to count
   *   }
   * })
  **/
  count<T extends MovementCountArgs>(
    args?: Prisma.Subset<T, MovementCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MovementCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Movement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MovementAggregateArgs>(args: Prisma.Subset<T, MovementAggregateArgs>): Prisma.PrismaPromise<GetMovementAggregateType<T>>

  /**
   * Group by Movement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MovementGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MovementGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MovementGroupByArgs['orderBy'] }
      : { orderBy?: MovementGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MovementGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMovementGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Movement model
 */
readonly fields: MovementFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Movement.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MovementClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lines<T extends Prisma.Movement$linesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Movement$linesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MovementLinePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  operation<T extends Prisma.OperationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OperationDefaultArgs<ExtArgs>>): Prisma.Prisma__OperationClient<runtime.Types.Result.GetResult<Prisma.$OperationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  createdBy<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  updatedBy<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Movement model
 */
export interface MovementFieldRefs {
  readonly id: Prisma.FieldRef<"Movement", 'Int'>
  readonly movementDate: Prisma.FieldRef<"Movement", 'DateTime'>
  readonly operationId: Prisma.FieldRef<"Movement", 'Int'>
  readonly createdById: Prisma.FieldRef<"Movement", 'Int'>
  readonly updatedById: Prisma.FieldRef<"Movement", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Movement", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Movement", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Movement findUnique
 */
export type MovementFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementInclude<ExtArgs> | null
  /**
   * Filter, which Movement to fetch.
   */
  where: Prisma.MovementWhereUniqueInput
}

/**
 * Movement findUniqueOrThrow
 */
export type MovementFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementInclude<ExtArgs> | null
  /**
   * Filter, which Movement to fetch.
   */
  where: Prisma.MovementWhereUniqueInput
}

/**
 * Movement findFirst
 */
export type MovementFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementInclude<ExtArgs> | null
  /**
   * Filter, which Movement to fetch.
   */
  where?: Prisma.MovementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Movements to fetch.
   */
  orderBy?: Prisma.MovementOrderByWithRelationInput | Prisma.MovementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Movements.
   */
  cursor?: Prisma.MovementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Movements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Movements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Movements.
   */
  distinct?: Prisma.MovementScalarFieldEnum | Prisma.MovementScalarFieldEnum[]
}

/**
 * Movement findFirstOrThrow
 */
export type MovementFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementInclude<ExtArgs> | null
  /**
   * Filter, which Movement to fetch.
   */
  where?: Prisma.MovementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Movements to fetch.
   */
  orderBy?: Prisma.MovementOrderByWithRelationInput | Prisma.MovementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Movements.
   */
  cursor?: Prisma.MovementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Movements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Movements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Movements.
   */
  distinct?: Prisma.MovementScalarFieldEnum | Prisma.MovementScalarFieldEnum[]
}

/**
 * Movement findMany
 */
export type MovementFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementInclude<ExtArgs> | null
  /**
   * Filter, which Movements to fetch.
   */
  where?: Prisma.MovementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Movements to fetch.
   */
  orderBy?: Prisma.MovementOrderByWithRelationInput | Prisma.MovementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Movements.
   */
  cursor?: Prisma.MovementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Movements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Movements.
   */
  skip?: number
  distinct?: Prisma.MovementScalarFieldEnum | Prisma.MovementScalarFieldEnum[]
}

/**
 * Movement create
 */
export type MovementCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementInclude<ExtArgs> | null
  /**
   * The data needed to create a Movement.
   */
  data: Prisma.XOR<Prisma.MovementCreateInput, Prisma.MovementUncheckedCreateInput>
}

/**
 * Movement createMany
 */
export type MovementCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Movements.
   */
  data: Prisma.MovementCreateManyInput | Prisma.MovementCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Movement createManyAndReturn
 */
export type MovementCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * The data used to create many Movements.
   */
  data: Prisma.MovementCreateManyInput | Prisma.MovementCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Movement update
 */
export type MovementUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementInclude<ExtArgs> | null
  /**
   * The data needed to update a Movement.
   */
  data: Prisma.XOR<Prisma.MovementUpdateInput, Prisma.MovementUncheckedUpdateInput>
  /**
   * Choose, which Movement to update.
   */
  where: Prisma.MovementWhereUniqueInput
}

/**
 * Movement updateMany
 */
export type MovementUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Movements.
   */
  data: Prisma.XOR<Prisma.MovementUpdateManyMutationInput, Prisma.MovementUncheckedUpdateManyInput>
  /**
   * Filter which Movements to update
   */
  where?: Prisma.MovementWhereInput
  /**
   * Limit how many Movements to update.
   */
  limit?: number
}

/**
 * Movement updateManyAndReturn
 */
export type MovementUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * The data used to update Movements.
   */
  data: Prisma.XOR<Prisma.MovementUpdateManyMutationInput, Prisma.MovementUncheckedUpdateManyInput>
  /**
   * Filter which Movements to update
   */
  where?: Prisma.MovementWhereInput
  /**
   * Limit how many Movements to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Movement upsert
 */
export type MovementUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementInclude<ExtArgs> | null
  /**
   * The filter to search for the Movement to update in case it exists.
   */
  where: Prisma.MovementWhereUniqueInput
  /**
   * In case the Movement found by the `where` argument doesn't exist, create a new Movement with this data.
   */
  create: Prisma.XOR<Prisma.MovementCreateInput, Prisma.MovementUncheckedCreateInput>
  /**
   * In case the Movement was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MovementUpdateInput, Prisma.MovementUncheckedUpdateInput>
}

/**
 * Movement delete
 */
export type MovementDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementInclude<ExtArgs> | null
  /**
   * Filter which Movement to delete.
   */
  where: Prisma.MovementWhereUniqueInput
}

/**
 * Movement deleteMany
 */
export type MovementDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Movements to delete
   */
  where?: Prisma.MovementWhereInput
  /**
   * Limit how many Movements to delete.
   */
  limit?: number
}

/**
 * Movement.lines
 */
export type Movement$linesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MovementLine
   */
  select?: Prisma.MovementLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MovementLine
   */
  omit?: Prisma.MovementLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementLineInclude<ExtArgs> | null
  where?: Prisma.MovementLineWhereInput
  orderBy?: Prisma.MovementLineOrderByWithRelationInput | Prisma.MovementLineOrderByWithRelationInput[]
  cursor?: Prisma.MovementLineWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MovementLineScalarFieldEnum | Prisma.MovementLineScalarFieldEnum[]
}

/**
 * Movement without action
 */
export type MovementDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Movement
   */
  select?: Prisma.MovementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Movement
   */
  omit?: Prisma.MovementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MovementInclude<ExtArgs> | null
}
