
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model Contact
 * 
 */
export type Contact = Prisma.ContactModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model Movement
 * 
 */
export type Movement = Prisma.MovementModel
/**
 * Model MovementLine
 * 
 */
export type MovementLine = Prisma.MovementLineModel
/**
 * Model Operation
 * 
 */
export type Operation = Prisma.OperationModel
/**
 * Model UserActivity
 * 
 */
export type UserActivity = Prisma.UserActivityModel
