
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Role'
export type * from './models/Contact'
export type * from './models/Product'
export type * from './models/Movement'
export type * from './models/MovementLine'
export type * from './models/Operation'
export type * from './models/Payment'
export type * from './models/PaymentMethod'
export type * from './models/Account'
export type * from './models/AccountEntry'
export type * from './models/UserActivity'
export type * from './commonInputTypes'